import { C } from './colors.js';

export const SEASON = 2026;

// Official MLB Pipeline in-season Farm System Rankings, published Aug. 16,
// 2026. This is a dated editorial ranking snapshot, not a live stat feed.
// Baseball America's public 2026 Top 100 methodology is retained as context
// only; no Baseball America subscription-only rank values are imported.
export const MLB_PIPELINE_FARM_SYSTEM_RANKINGS = Object.freeze({
  season: 2026,
  publishedAt: '2026-08-16',
  source: 'MLB Pipeline',
  sourceUrl: 'https://www.mlb.com/news/in-season-farm-system-rankings-2026',
  methodologyReference: {
    source: 'Baseball America',
    sourceUrl: 'https://www.baseballamerica.com/rankings/2026-top-100-prospects/',
    use: 'Public methodology reference only; subscription-only ranking values are not imported.',
  },
  ranks: Object.freeze({
    LAD:1, TB:2, MIL:3, STL:4, SF:5, WSH:6, BAL:7, DET:8, SEA:9, MIA:10,
    MIN:11, CLE:12, PIT:13, ATH:14, CWS:15, COL:16, LAA:17, NYM:18, KC:19, TEX:20,
    ATL:21, TOR:22, CIN:23, BOS:24, ARI:25, PHI:26, NYY:27, CHC:28, HOU:29, SD:30,
  }),
});

export const TEAMS = {
  lad: { name:'Los Angeles Dodgers',  abbr:'LAD', color:'#005A9C', id:119,  w: 73, l: 48, pct: 0.603, rs: 606, ra: 464, era:2.98, ops:.802, hr:98,  avg:.268, obp:.352, slg:.450, whip:1.06, k:628, sb:54, wrcPlus:124, fip:3.11, drs:18, bsr:14.2, war:22.1, div:'NL West' },
  nyy: { name:'New York Yankees',     abbr:'NYY', color:'#003087', id:147,  w: 68, l: 52, pct: 0.567, rs: 545, ra: 455, era:3.21, ops:.778, hr:104, avg:.249, obp:.336, slg:.442, whip:1.12, k:598, sb:34, wrcPlus:116, fip:3.34, drs:12, bsr:9.8,  war:19.4, div:'AL East' },
  atl: { name:'Atlanta Braves',       abbr:'ATL', color:'#CE1141', id:144,  w: 73, l: 48, pct: 0.603, rs: 591, ra: 467, era:3.44, ops:.761, hr:88,  avg:.255, obp:.330, slg:.431, whip:1.18, k:572, sb:62, wrcPlus:110, fip:3.52, drs:8,  bsr:18.1, war:17.2, div:'NL East' },
  hou: { name:'Houston Astros',       abbr:'HOU', color:'#002D62', id:117,  w: 62, l: 60, pct: 0.508, rs: 559, ra: 586, era:3.61, ops:.751, hr:82,  avg:.252, obp:.322, slg:.429, whip:1.21, k:551, sb:48, wrcPlus:107, fip:3.71, drs:14, bsr:12.4, war:16.1, div:'AL West' },
  sea: { name:'Seattle Mariners',     abbr:'SEA', color:'#005C5C', id:136,  w: 56, l: 65, pct: 0.463, rs: 468, ra: 495, era:3.48, ops:.738, hr:74,  avg:.244, obp:.316, slg:.422, whip:1.16, k:612, sb:41, wrcPlus:103, fip:3.44, drs:22, bsr:10.2, war:15.8, div:'AL West' },
  bos: { name:'Boston Red Sox',       abbr:'BOS', color:'#BD3039', id:111,  w: 64, l: 56, pct: 0.533, rs: 531, ra: 452, era:3.72, ops:.749, hr:91,  avg:.258, obp:.334, slg:.441, whip:1.23, k:541, sb:58, wrcPlus:108, fip:3.81, drs:6,  bsr:15.1, war:14.8, div:'AL East' },
  cle: { name:'Cleveland Guardians',  abbr:'CLE', color:'#E31937', id:114,  w: 59, l: 62, pct: 0.488, rs: 483, ra: 510, era:3.55, ops:.731, hr:72,  avg:.249, obp:.318, slg:.413, whip:1.19, k:579, sb:44, wrcPlus:101, fip:3.61, drs:16, bsr:11.8, war:13.9, div:'AL Central' },
  bal: { name:'Baltimore Orioles',    abbr:'BAL', color:'#DF4601', id:110,  w: 58, l: 63, pct: 0.479, rs: 543, ra: 579, era:3.81, ops:.742, hr:88,  avg:.252, obp:.320, slg:.422, whip:1.24, k:534, sb:52, wrcPlus:104, fip:3.92, drs:10, bsr:14.4, war:13.2, div:'AL East' },
  sd:  { name:'San Diego Padres',     abbr:'SD',  color:'#2F241D', id:135,  w: 65, l: 57, pct: 0.533, rs: 522, ra: 521, era:4.10, ops:.702, hr:134, avg:.238, obp:.314, slg:.388, whip:1.32, k:992, sb:123, wrcPlus:100, fip:4.12, drs:14, bsr:16.2, war:24.5, div:'NL West' },
  phi: { name:'Philadelphia Phillies',abbr:'PHI', color:'#E81828', id:143,  w: 64, l: 58, pct: 0.525, rs: 535, ra: 542, era:3.91, ops:.724, hr:82,  avg:.248, obp:.314, slg:.410, whip:1.26, k:548, sb:38, wrcPlus:98,  fip:3.98, drs:8,  bsr:10.4, war:12.1, div:'NL East' },
  laa: { name:'Los Angeles Angels', abbr:'LAA', color:'#003263', id:108,  w: 47, l: 74, pct: 0.388, rs: 493, ra: 583, era:3.99, ops:0.695, hr:74,  avg:0.244, obp:0.311, slg:0.384, whip:1.19, k:565, sb:65, wrcPlus:88, fip:3.93, drs:-11, bsr:7.1, war:1.8, div:'AL West' },
  ari: { name:'Arizona Diamondbacks', abbr:'ARI', color:'#A71930', id:109,  w: 64, l: 58, pct: 0.525, rs: 552, ra: 541, era:3.76, ops:0.736, hr:80,  avg:0.243, obp:0.317, slg:0.419, whip:1.14, k:588, sb:57, wrcPlus:97, fip:3.82, drs:-8, bsr:8.7, war:6.4, div:'NL West' },
  chc: { name:'Chicago Cubs', abbr:'CHC', color:'#0E3386', id:112,  w: 71, l: 50, pct: 0.587, rs: 634, ra: 519, era:4.07, ops:0.714, hr:74,  avg:0.238, obp:0.309, slg:0.405, whip:1.18, k:546, sb:54, wrcPlus:92, fip:4.1, drs:-6, bsr:8.9, war:4.5, div:'NL Central' },
  cin: { name:'Cincinnati Reds', abbr:'CIN', color:'#C6011F', id:113,  w: 57, l: 62, pct: 0.479, rs: 487, ra: 565, era:3.86, ops:0.735, hr:68,  avg:0.249, obp:0.319, slg:0.416, whip:1.13, k:567, sb:64, wrcPlus:95, fip:3.98, drs:2, bsr:9.8, war:8.0, div:'NL Central' },
  col: { name:'Colorado Rockies', abbr:'COL', color:'#333366', id:115,  w: 48, l: 73, pct: 0.397, rs: 577, ra: 693, era:3.96, ops:0.721, hr:72,  avg:0.244, obp:0.320, slg:0.401, whip:1.15, k:517, sb:38, wrcPlus:94, fip:3.87, drs:-5, bsr:15.1, war:7.0, div:'NL West' },
  det: { name:'Detroit Tigers', abbr:'DET', color:'#0C2340', id:116,  w: 59, l: 61, pct: 0.492, rs: 549, ra: 462, era:3.96, ops:0.703, hr:79,  avg:0.248, obp:0.321, slg:0.382, whip:1.17, k:551, sb:56, wrcPlus:94, fip:3.84, drs:-6, bsr:9.2, war:5.3, div:'AL Central' },
  kc: { name:'Kansas City Royals', abbr:'KC', color:'#004687', id:118,  w: 49, l: 73, pct: 0.402, rs: 503, ra: 617, era:3.91, ops:0.707, hr:71,  avg:0.247, obp:0.323, slg:0.384, whip:1.15, k:500, sb:50, wrcPlus:86, fip:4.05, drs:-11, bsr:10.5, war:3.1, div:'AL Central' },
  wsh: { name:'Washington Nationals', abbr:'WSH', color:'#AB0003', id:120,  w: 59, l: 63, pct: 0.484, rs: 655, ra: 639, era:4.2, ops:0.692, hr:65,  avg:0.247, obp:0.324, slg:0.368, whip:1.18, k:559, sb:57, wrcPlus:85, fip:4.09, drs:-5, bsr:17.7, war:3.5, div:'NL East' },
  nym: { name:'New York Mets', abbr:'NYM', color:'#002D72', id:121,  w: 53, l: 69, pct: 0.434, rs: 510, ra: 557, era:3.61, ops:0.731, hr:75,  avg:0.244, obp:0.314, slg:0.417, whip:1.13, k:566, sb:66, wrcPlus:97, fip:3.57, drs:-1, bsr:11.3, war:6.9, div:'NL East' },
  ath: { name:'Athletics', abbr:'ATH', color:'#003831', id:133,  w: 47, l: 74, pct: 0.388, rs: 524, ra: 704, era:3.81, ops:0.710, hr:65,  avg:0.237, obp:0.312, slg:0.398, whip:1.13, k:503, sb:50, wrcPlus:88, fip:3.88, drs:-9, bsr:11.8, war:5.2, div:'AL West' },
  pit: { name:'Pittsburgh Pirates', abbr:'PIT', color:'#27251F', id:134,  w: 58, l: 64, pct: 0.475, rs: 604, ra: 591, era:4.08, ops:0.684, hr:68,  avg:0.243, obp:0.314, slg:0.370, whip:1.16, k:557, sb:55, wrcPlus:90, fip:4.09, drs:-14, bsr:14.7, war:4.3, div:'NL Central' },
  sf: { name:'San Francisco Giants', abbr:'SF', color:'#FD5A1E', id:137,  w: 50, l: 71, pct: 0.413, rs: 493, ra: 557, era:3.77, ops:0.705, hr:72,  avg:0.240, obp:0.318, slg:0.387, whip:1.13, k:554, sb:66, wrcPlus:95, fip:3.79, drs:-1, bsr:17.6, war:6.9, div:'NL West' },
  stl: { name:'St. Louis Cardinals', abbr:'STL', color:'#C41E3A', id:138,  w: 61, l: 60, pct: 0.504, rs: 529, ra: 530, era:3.49, ops:0.717, hr:73,  avg:0.245, obp:0.324, slg:0.393, whip:1.11, k:526, sb:65, wrcPlus:101, fip:3.5, drs:5, bsr:12.7, war:8.9, div:'NL Central' },
  tb: { name:'Tampa Bay Rays', abbr:'TB', color:'#092C5C', id:139,  w: 74, l: 46, pct: 0.617, rs: 549, ra: 487, era:3.76, ops:0.697, hr:72,  avg:0.241, obp:0.309, slg:0.388, whip:1.13, k:507, sb:50, wrcPlus:95, fip:3.9, drs:-1, bsr:6.8, war:4.1, div:'AL East' },
  tex: { name:'Texas Rangers', abbr:'TEX', color:'#003278', id:140,  w: 60, l: 61, pct: 0.496, rs: 497, ra: 531, era:3.62, ops:0.713, hr:77,  avg:0.241, obp:0.316, slg:0.397, whip:1.14, k:568, sb:44, wrcPlus:96, fip:3.7, drs:-5, bsr:7.6, war:8.2, div:'AL West' },
  tor: { name:'Toronto Blue Jays', abbr:'TOR', color:'#134A8E', id:141,  w: 59, l: 63, pct: 0.484, rs: 482, ra: 536, era:3.93, ops:0.715, hr:66,  avg:0.247, obp:0.315, slg:0.400, whip:1.18, k:509, sb:62, wrcPlus:87, fip:3.96, drs:-9, bsr:7.9, war:5.0, div:'AL East' },
  min: { name:'Minnesota Twins', abbr:'MIN', color:'#002B5C', id:142,  w: 60, l: 62, pct: 0.492, rs: 571, ra: 603, era:3.81, ops:0.728, hr:81,  avg:0.242, obp:0.317, slg:0.411, whip:1.16, k:578, sb:52, wrcPlus:92, fip:3.66, drs:-6, bsr:13.3, war:7.3, div:'AL Central' },
  cws: { name:'Chicago White Sox', abbr:'CWS', color:'#27251F', id:145,  w: 62, l: 57, pct: 0.521, rs: 566, ra: 525, era:3.86, ops:0.729, hr:79,  avg:0.239, obp:0.314, slg:0.415, whip:1.16, k:561, sb:65, wrcPlus:90, fip:3.81, drs:-8, bsr:11.3, war:7.0, div:'AL Central' },
  mia: { name:'Miami Marlins', abbr:'MIA', color:'#00A3E0', id:146,  w: 62, l: 59, pct: 0.512, rs: 534, ra: 511, era:3.42, ops:0.733, hr:72,  avg:0.250, obp:0.324, slg:0.409, whip:1.08, k:606, sb:59, wrcPlus:96, fip:3.63, drs:4, bsr:16.8, war:7.7, div:'NL East' },
  mil: { name:'Milwaukee Brewers', abbr:'MIL', color:'#12284B', id:158,  w: 74, l: 47, pct: 0.612, rs: 592, ra: 462, era:3.72, ops:0.741, hr:72,  avg:0.249, obp:0.327, slg:0.414, whip:1.11, k:567, sb:47, wrcPlus:95, fip:3.92, drs:-6, bsr:17.1, war:8.6, div:'NL Central' },
};

export function sortTeamsByLeagueDivisionName(entries = Object.entries(TEAMS)) {
  const leagueRank = { AL: 0, NL: 1 };
  return [...entries].sort(([, a], [, b]) => {
    const [aLeague = '', ...aDivisionParts] = String(a?.div || '').split(' ');
    const [bLeague = '', ...bDivisionParts] = String(b?.div || '').split(' ');
    const leagueCompare = (leagueRank[aLeague] ?? 99) - (leagueRank[bLeague] ?? 99);
    if (leagueCompare !== 0) return leagueCompare;
    const divisionCompare = aDivisionParts.join(' ').localeCompare(bDivisionParts.join(' '), 'en', { sensitivity: 'base' });
    if (divisionCompare !== 0) return divisionCompare;
    return String(a?.name || '').localeCompare(String(b?.name || ''), 'en', { sensitivity: 'base' });
  });
}

// ─── TOP 100 PROSPECTS — Live from MLB.com/prospects/stats/top-prospects ──────
// Batters: Rk, Name, Team, Age, Level, PA, AB, R, H, 2B, 3B, HR, RBI, BB, SO, SB, AVG, OBP, SLG, OPS
// Pitchers: Rk, Name, Team, Age, Level, G, IP, H, BB, SO, ERA, WHIP, W, L
// Last updated: June 2026

export const PROSPECT_BATTERS = [
  { rank:1,  mlbId:805811, name:'Bryce Eldridge',    pos:'DH', team:'SF',  age:21, level:'MLB/AAA', pa:318, ab:277, r:38, h:68,  d:15, t:0, hr:12, rbi:29, bb:40, so:85, sb:1,  avg:.245, obp:.340, slg:.430, ops:.770 },
  { rank:3,  mlbId:815908, name:'Jesús Made',        pos:'SS', team:'MIL', age:19, level:'AA',      pa:234, ab:207, r:36, h:57,  d:8,  t:4, hr:6,  rbi:40, bb:25, so:33, sb:19, avg:.275, obp:.350, slg:.440, ops:.790 },
  { rank:2,  mlbId:815888, name:'Leo De Vries',       pos:'SS', team:'ATH', age:19, level:'AA',      pa:223, ab:192, r:33, h:55,  d:6,  t:0, hr:5,  rbi:22, bb:23, so:46, sb:18, avg:.286, obp:.371, slg:.396, ops:.767 },
  { rank:4,  mlbId:816113, name:'Eli Willits',        pos:'SS', team:'WSH', age:18, level:'A',       pa:232, ab:190, r:48, h:57,  d:14, t:3, hr:6,  rbi:37, bb:38, so:54, sb:29, avg:.300, obp:.418, slg:.500, ops:.918 },
  { rank:5,  mlbId:806068, name:'Colt Emerson',       pos:'SS', team:'SEA', age:20, level:'A+/AA',   pa:238, ab:207, r:35, h:52,  d:13, t:2, hr:11, rbi:36, bb:22, so:67, sb:10, avg:.251, obp:.339, slg:.493, ops:.832 },
  { rank:7,  mlbId:703601, name:'Max Clark',          pos:'OF', team:'DET', age:21, level:'AAA',     pa:249, ab:218, r:37, h:56,  d:13, t:2, hr:4,  rbi:24, bb:27, so:40, sb:12, avg:.257, obp:.341, slg:.390, ops:.731 },
  { rank:8,  mlbId:800543, name:'Josue De Paula',     pos:'OF', team:'LAD', age:21, level:'AA',      pa:255, ab:216, r:48, h:69,  d:20, t:0, hr:10, rbi:53, bb:37, so:33, sb:16, avg:.319, obp:.420, slg:.551, ops:.971 },
  { rank:10, mlbId:808265, name:'Franklin Arias',     pos:'OF', team:'BOS', age:20, level:'AA',      pa:203, ab:177, r:32, h:55,  d:8,  t:1, hr:13, rbi:34, bb:19, so:26, sb:4,  avg:.311, obp:.389, slg:.588, ops:.977 },
  { rank:11, mlbId:805805, name:'Walker Jenkins',     pos:'OF', team:'MIN', age:21, level:'AAA',     pa:111, ab:90,  r:15, h:23,  d:6,  t:0, hr:2,  rbi:9,  bb:19, so:18, sb:5,  avg:.256, obp:.396, slg:.389, ops:.785 },
  { rank:13, mlbId:815352, name:'Caleb Bonemer',      pos:'OF', team:'CWS', age:20, level:'A+',      pa:245, ab:195, r:48, h:49,  d:15, t:1, hr:17, rbi:42, bb:33, so:72, sb:8,  avg:.251, obp:.396, slg:.600, ops:.996 },
  { rank:15, mlbId:815787, name:'Ethan Holliday',     pos:'SS', team:'COL', age:19, level:'A',       pa:152, ab:122, r:29, h:32,  d:5,  t:2, hr:9,  rbi:32, bb:23, so:43, sb:1,  avg:.262, obp:.395, slg:.557, ops:.952 },
  { rank:16, mlbId:821270, name:'Luis Peña',          pos:'OF', team:'MIL', age:19, level:'A/A+',    pa:93,  ab:74,  r:22, h:25,  d:2,  t:2, hr:1,  rbi:11, bb:16, so:16, sb:12, avg:.338, obp:.452, slg:.459, ops:.911 },
  { rank:17, mlbId:814307, name:'Zyhir Hope',         pos:'OF', team:'DET', age:21, level:'AA',      pa:242, ab:218, r:34, h:64,  d:10, t:1, hr:13, rbi:55, bb:20, so:60, sb:8,  avg:.294, obp:.351, slg:.528, ops:.879 },
  { rank:18, mlbId:806146, name:'George Lombard Jr.', pos:'OF', team:'NYY', age:21, level:'A+/AA',   pa:257, ab:208, r:42, h:51,  d:14, t:0, hr:6,  rbi:22, bb:44, so:57, sb:11, avg:.245, obp:.381, slg:.399, ops:.780 },
  { rank:21, mlbId:695731, name:'Braden Montgomery',  pos:'OF', team:'CWS', age:23, level:'AA/AAA',  pa:258, ab:210, r:52, h:66,  d:13, t:3, hr:10, rbi:41, bb:39, so:64, sb:5,  avg:.314, obp:.422, slg:.548, ops:.970 },
  { rank:22, mlbId:823787, name:'Rainiel Rodriguez',  pos:'2B', team:'STL', age:19, level:'A/A+',    pa:216, ab:179, r:34, h:46,  d:9,  t:1, hr:5,  rbi:28, bb:30, so:50, sb:6,  avg:.257, obp:.375, slg:.402, ops:.777 },
  { rank:23, mlbId:806957, name:'Alfredo Duno',       pos:'OF', team:'CIN', age:20, level:'A+',      pa:221, ab:181, r:31, h:46,  d:10, t:0, hr:12, rbi:31, bb:37, so:60, sb:1,  avg:.254, obp:.385, slg:.508, ops:.893 },
  { rank:27, mlbId:703155, name:'Lazaro Montes',      pos:'OF', team:'SEA', age:21, level:'AA',      pa:235, ab:200, r:44, h:47,  d:8,  t:1, hr:17, rbi:43, bb:30, so:66, sb:4,  avg:.235, obp:.345, slg:.540, ops:.885 },
  { rank:28, mlbId:829034, name:'Josuar Gonzalez',    pos:'OF', team:'SF',  age:18, level:'ROK',     pa:49,  ab:38,  r:15, h:16,  d:4,  t:1, hr:1,  rbi:11, bb:11, so:10, sb:4,  avg:.421, obp:.551, slg:.658, ops:1.209 },
  { rank:29, mlbId:828098, name:'JoJo Parker',        pos:'SS', team:'TOR', age:19, level:'A',       pa:220, ab:177, r:30, h:40,  d:13, t:0, hr:4,  rbi:25, bb:37, so:57, sb:13, avg:.226, obp:.373, slg:.367, ops:.740 },
  { rank:30, mlbId:814439, name:'Ryan Waldschmidt',   pos:'OF', team:'ARI', age:23, level:'A+/AA',   pa:261, ab:225, r:40, h:64,  d:16, t:4, hr:3,  rbi:30, bb:26, so:73, sb:11, avg:.284, obp:.371, slg:.431, ops:.802 },
  { rank:31, mlbId:805999, name:'A.J. Ewing',         pos:'SS', team:'NYM', age:21, level:'A/A+/AA', pa:231, ab:194, r:36, h:59,  d:10, t:3, hr:3,  rbi:18, bb:33, so:51, sb:24, avg:.304, obp:.402, slg:.433, ops:.835 },
  { rank:32, mlbId:804109, name:'Aiva Arquette',      pos:'OF', team:'MIA', age:22, level:'A+/AA',   pa:118, ab:107, r:15, h:26,  d:6,  t:2, hr:4,  rbi:22, bb:10, so:27, sb:7,  avg:.243, obp:.314, slg:.449, ops:.763 },
  { rank:34, mlbId:821273, name:'Edward Florentino',  pos:'OF', team:'PIT', age:19, level:'A/A+',    pa:168, ab:134, r:31, h:30,  d:4,  t:0, hr:8,  rbi:28, bb:29, so:40, sb:3,  avg:.224, obp:.363, slg:.433, ops:.796 },
  { rank:35, mlbId:808234, name:'Eduardo Quintero',   pos:'OF', team:'LAD', age:20, level:'A+',      pa:212, ab:181, r:42, h:52,  d:12, t:0, hr:2,  rbi:25, bb:29, so:52, sb:24, avg:.287, obp:.392, slg:.387, ops:.779 },
  { rank:36, mlbId:701785, name:'Kaelen Culpepper',   pos:'SS', team:'MIN', age:23, level:'AAA',     pa:267, ab:226, r:50, h:60,  d:9,  t:0, hr:14, rbi:40, bb:34, so:49, sb:13, avg:.265, obp:.371, slg:.491, ops:.862 },
  { rank:39, mlbId:701527, name:'Mike Sirota',        pos:'1B', team:'LAD', age:22, level:'A+/AA',   pa:240, ab:186, r:51, h:63,  d:17, t:1, hr:10, rbi:36, bb:50, so:51, sb:10, avg:.339, obp:.488, slg:.602, ops:1.090 },
  { rank:40, mlbId:815394, name:'Theo Gillen',        pos:'OF', team:'TB',  age:20, level:'A+',      pa:204, ab:169, r:41, h:55,  d:9,  t:3, hr:9,  rbi:32, bb:28, so:51, sb:22, avg:.325, obp:.431, slg:.574, ops:1.005 },
  { rank:41, mlbId:691788, name:'Joe Mack',           pos:'C',  team:'MIA', age:23, level:'A+/AA',   pa:193, ab:165, r:18, h:38,  d:6,  t:0, hr:4,  rbi:22, bb:25, so:50, sb:1,  avg:.230, obp:.330, slg:.339, ops:.669 },
  { rank:42, mlbId:806953, name:'Eduardo Tait',       pos:'SS', team:'MIN', age:19, level:'A+',      pa:219, ab:191, r:32, h:41,  d:10, t:0, hr:9,  rbi:31, bb:21, so:54, sb:0,  avg:.215, obp:.301, slg:.408, ops:.709 },
  { rank:43, mlbId:800614, name:'Bryce Rainer',       pos:'OF', team:'DET', age:20, level:'A/A+',    pa:200, ab:171, r:23, h:39,  d:11, t:1, hr:4,  rbi:25, bb:27, so:77, sb:10, avg:.228, obp:.330, slg:.374, ops:.704 },
  { rank:44, mlbId:694197, name:'Angel Genao',        pos:'SS', team:'CLE', age:22, level:'A+/AA',   pa:226, ab:190, r:35, h:49,  d:10, t:1, hr:7,  rbi:23, bb:30, so:45, sb:4,  avg:.258, obp:.358, slg:.432, ops:.790 },
  { rank:45, mlbId:703197, name:'Michael Arroyo',     pos:'SS', team:'SEA', age:21, level:'AA',      pa:198, ab:175, r:25, h:48,  d:6,  t:0, hr:7,  rbi:30, bb:14, so:39, sb:7,  avg:.274, obp:.343, slg:.429, ops:.772 },
  { rank:49, mlbId:806956, name:'Ethan Salas',        pos:'C',  team:'SD',  age:20, level:'AA',      pa:206, ab:182, r:30, h:53,  d:10, t:0, hr:7,  rbi:31, bb:18, so:32, sb:12, avg:.291, obp:.346, slg:.462, ops:.808 },
  { rank:50, mlbId:815814, name:'Billy Carlson',      pos:'SS', team:'CWS', age:19, level:'A',       pa:177, ab:144, r:25, h:37,  d:10, t:1, hr:0,  rbi:11, bb:27, so:45, sb:8,  avg:.257, obp:.386, slg:.340, ops:.726 },
  { rank:51, mlbId:691181, name:'Emmanuel Rodriguez', pos:'OF', team:'MIN', age:23, level:'AAA',     pa:108, ab:81,  r:15, h:20,  d:3,  t:0, hr:6,  rbi:18, bb:23, so:31, sb:3,  avg:.247, obp:.417, slg:.506, ops:.923 },
  { rank:52, mlbId:805810, name:'Blake Mitchell',     pos:'C',  team:'KC',  age:21, level:'A+',      pa:222, ab:157, r:46, h:32,  d:7,  t:0, hr:10, rbi:30, bb:59, so:76, sb:12, avg:.204, obp:.423, slg:.439, ops:.862 },
  { rank:53, mlbId:805796, name:'Arjun Nimmala',      pos:'SS', team:'LAA', age:20, level:'A/A+',    pa:177, ab:152, r:24, h:41,  d:13, t:0, hr:4,  rbi:22, bb:23, so:40, sb:5,  avg:.270, obp:.367, slg:.434, ops:.801 },
  { rank:54, mlbId:815896, name:'Emil Morales',       pos:'OF', team:'LAD', age:19, level:'A/A+',    pa:249, ab:221, r:35, h:65,  d:17, t:3, hr:10, rbi:53, bb:20, so:65, sb:3,  avg:.294, obp:.357, slg:.534, ops:.891 },
  { rank:55, mlbId:836582, name:'Luis Hernández',     pos:'OF', team:'SF',  age:17, level:'ROK',     pa:107, ab:94,  r:19, h:29,  d:9,  t:3, hr:5,  rbi:23, bb:11, so:18, sb:3,  avg:.309, obp:.383, slg:.628, ops:1.011 },
  { rank:56, mlbId:806252, name:'Ralphy Velazquez',   pos:'OF', team:'CLE', age:21, level:'A+/AA',   pa:228, ab:199, r:30, h:59,  d:14, t:4, hr:8,  rbi:33, bb:25, so:46, sb:1,  avg:.296, obp:.386, slg:.528, ops:.914 },
  { rank:57, mlbId:702518, name:'Jett Williams',      pos:'SS', team:'MIL', age:22, level:'AAA',     pa:269, ab:228, r:42, h:51,  d:7,  t:4, hr:5,  rbi:28, bb:36, so:59, sb:12, avg:.224, obp:.338, slg:.355, ops:.693 },
  { rank:61, mlbId:815929, name:'Jhonny Level',       pos:'OF', team:'SF',  age:19, level:'A/A+',    pa:246, ab:218, r:40, h:72,  d:17, t:2, hr:10, rbi:49, bb:17, so:41, sb:12, avg:.330, obp:.394, slg:.564, ops:.958 },
  { rank:62, mlbId:829162, name:'Steele Hall',        pos:'SS', team:'CIN', age:18, level:'ROK',     pa:124, ab:98,  r:26, h:28,  d:9,  t:1, hr:4,  rbi:19, bb:19, so:29, sb:11, avg:.286, obp:.407, slg:.520, ops:.927 },
  { rank:63, mlbId:806198, name:'Cooper Pratt',       pos:'2B', team:'MIL', age:21, level:'AAA',     pa:241, ab:202, r:29, h:50,  d:6,  t:4, hr:5,  rbi:29, bb:33, so:36, sb:16, avg:.248, obp:.360, slg:.391, ops:.751 },
  { rank:65, mlbId:695491, name:'Joshua Báez',        pos:'OF', team:'STL', age:22, level:'AAA',     pa:252, ab:225, r:44, h:62,  d:13, t:3, hr:17, rbi:45, bb:19, so:81, sb:11, avg:.276, obp:.349, slg:.587, ops:.936 },
  { rank:66, mlbId:825582, name:'Nate George',        pos:'SS', team:'BAL', age:20, level:'A+',      pa:94,  ab:82,  r:18, h:24,  d:3,  t:0, hr:1,  rbi:8,  bb:10, so:18, sb:15, avg:.293, obp:.372, slg:.366, ops:.738 },
  { rank:70, mlbId:694876, name:'Cooper Ingle',       pos:'C',  team:'CLE', age:24, level:'AAA',     pa:169, ab:130, r:28, h:39,  d:6,  t:1, hr:9,  rbi:34, bb:37, so:37, sb:1,  avg:.300, obp:.456, slg:.569, ops:1.025 },
  { rank:71, mlbId:806071, name:'Jonny Farmelo',      pos:'OF', team:'SEA', age:21, level:'A+',      pa:252, ab:206, r:45, h:53,  d:9,  t:5, hr:7,  rbi:21, bb:42, so:66, sb:15, avg:.257, obp:.389, slg:.451, ops:.840 },
  { rank:72, mlbId:809707, name:'Charlie Condon',     pos:'OF', team:'COL', age:23, level:'AAA',     pa:253, ab:205, r:46, h:51,  d:13, t:1, hr:9,  rbi:29, bb:39, so:61, sb:5,  avg:.249, obp:.383, slg:.454, ops:.837 },
  { rank:76, mlbId:829037, name:'Kevin Alvarez',      pos:'3B', team:'HOU', age:18, level:'A',       pa:193, ab:176, r:29, h:46,  d:11, t:2, hr:5,  rbi:24, bb:11, so:32, sb:4,  avg:.261, obp:.311, slg:.432, ops:.743 },
  { rank:78, mlbId:821041, name:'Roldy Brito',        pos:'OF', team:'COL', age:19, level:'A',       pa:262, ab:239, r:49, h:78,  d:16, t:4, hr:6,  rbi:50, bb:17, so:43, sb:9,  avg:.326, obp:.368, slg:.502, ops:.870 },
  { rank:79, mlbId:815617, name:'Kayson Cunningham',  pos:'2B', team:'ARI', age:19, level:'A',       pa:207, ab:176, r:45, h:67,  d:11, t:4, hr:1,  rbi:27, bb:30, so:38, sb:10, avg:.381, obp:.471, slg:.506, ops:.977 },
  { rank:80, mlbId:800473, name:'Jefferson Rojas',    pos:'OF', team:'NYM', age:21, level:'AA',      pa:190, ab:167, r:29, h:45,  d:9,  t:1, hr:9,  rbi:30, bb:20, so:38, sb:8,  avg:.269, obp:.346, slg:.497, ops:.843 },
  { rank:82, mlbId:699393, name:'Pedro Ramírez',      pos:'OF', team:'CHC', age:22, level:'A+/AA',   pa:221, ab:192, r:36, h:58,  d:12, t:1, hr:9,  rbi:41, bb:24, so:33, sb:19, avg:.302, obp:.386, slg:.516, ops:.902 },
  { rank:86, mlbId:807083, name:'Nathan Flewelling',  pos:'OF', team:'TB',  age:19, level:'A+',      pa:214, ab:181, r:30, h:47,  d:8,  t:1, hr:10, rbi:33, bb:28, so:53, sb:3,  avg:.260, obp:.369, slg:.481, ops:.850 },
  { rank:87, mlbId:826723, name:'Ronny Cruz',         pos:'SS', team:'WSH', age:19, level:'A/A+',    pa:232, ab:207, r:37, h:52,  d:8,  t:2, hr:7,  rbi:28, bb:19, so:61, sb:21, avg:.251, obp:.328, slg:.411, ops:.739 },
  { rank:89, mlbId:702610, name:'Ike Irish',          pos:'OF', team:'BAL', age:22, level:'A+',      pa:186, ab:158, r:35, h:39,  d:8,  t:0, hr:7,  rbi:30, bb:23, so:47, sb:11, avg:.247, obp:.355, slg:.430, ops:.785 },
  { rank:91, mlbId:800325, name:'Luis Lara',          pos:'OF', team:'MIL', age:21, level:'AAA',     pa:247, ab:204, r:49, h:69,  d:8,  t:2, hr:7,  rbi:27, bb:39, so:32, sb:18, avg:.338, obp:.447, slg:.500, ops:.947 },
  { rank:92, mlbId:815843, name:'Josh Hammond',       pos:'SS', team:'KC',  age:19, level:'A',       pa:226, ab:205, r:35, h:56,  d:16, t:3, hr:3,  rbi:24, bb:20, so:54, sb:15, avg:.273, obp:.336, slg:.424, ops:.760 },
  { rank:93, mlbId:821100, name:'Justin Gonzales',    pos:'OF', team:'BOS', age:19, level:'A+',      pa:213, ab:189, r:35, h:52,  d:8,  t:2, hr:7,  rbi:27, bb:18, so:35, sb:0,  avg:.275, obp:.357, slg:.450, ops:.807 },
  { rank:94, mlbId:804560, name:'Charles Davalan',    pos:'OF', team:'LAD', age:22, level:'A+',      pa:233, ab:190, r:45, h:53,  d:14, t:0, hr:7,  rbi:30, bb:32, so:26, sb:11, avg:.279, obp:.403, slg:.463, ops:.866 },
  { rank:95, mlbId:815832, name:'Xavier Neyens',      pos:'1B', team:'HOU', age:19, level:'A',       pa:195, ab:154, r:27, h:37,  d:3,  t:0, hr:8,  rbi:22, bb:39, so:64, sb:10, avg:.240, obp:.400, slg:.416, ops:.816 },
  { rank:96, mlbId:695490, name:'Edwin Arroyo',       pos:'SS', team:'CIN', age:22, level:'A+/AA',   pa:270, ab:234, r:42, h:74,  d:9,  t:5, hr:11, rbi:35, bb:20, so:49, sb:9,  avg:.316, obp:.376, slg:.538, ops:.914 },
  { rank:97, mlbId:803849, name:'Devin Fitz-Gerald',  pos:'SS', team:'WSH', age:20, level:'A+',      pa:237, ab:202, r:42, h:54,  d:11, t:3, hr:12, rbi:37, bb:30, so:42, sb:11, avg:.267, obp:.373, slg:.530, ops:.903 },
  { rank:98, mlbId:806958, name:'Felnin Celesten',    pos:'OF', team:'SEA', age:20, level:'A+',      pa:228, ab:186, r:39, h:59,  d:12, t:1, hr:5,  rbi:32, bb:34, so:44, sb:13, avg:.317, obp:.430, slg:.473, ops:.903 },
  { rank:99, mlbId:814409, name:'Seaver King',        pos:'SS', team:'WSH', age:23, level:'A+/AA',   pa:238, ab:204, r:40, h:65,  d:13, t:4, hr:8,  rbi:42, bb:25, so:49, sb:7,  avg:.319, obp:.397, slg:.539, ops:.936 },
];

export const PROSPECT_PITCHERS = [
  { rank:3,  mlbId:815825, name:'Seth Hernandez',     pos:'RHP', team:'PIT', age:19, level:'A/A+',   g:10, ip:45.2, h:23,  bb:20, so:76,  era:2.17, whip:0.94, w:4, l:1 },
  { rank:6,  mlbId:807739, name:'Kade Anderson',      pos:'LHP', team:'SEA', age:21, level:'AA',     g:10, ip:49.0, h:27,  bb:7,  so:76,  era:1.29, whip:0.69, w:5, l:0 },
  { rank:12, mlbId:806258, name:'Thomas White',       pos:'LHP', team:'MIA', age:21, level:'A/AA',   g:7,  ip:24.2, h:21,  bb:15, so:35,  era:4.01, whip:1.46, w:0, l:3 },
  { rank:19, mlbId:815549, name:'Ryan Sloan',         pos:'RHP', team:'SEA', age:20, level:'AA',     g:10, ip:40.2, h:44,  bb:11, so:51,  era:5.09, whip:1.35, w:1, l:2 },
  { rank:20, mlbId:824604, name:'Liam Doyle',         pos:'LHP', team:'STL', age:22, level:'AA',     g:10, ip:39.0, h:38,  bb:21, so:54,  era:5.54, whip:1.51, w:1, l:3 },
  { rank:24, mlbId:702273, name:'Noah Schultz',       pos:'LHP', team:'CWS', age:22, level:'A+/AA',  g:11, ip:52.2, h:34,  bb:24, so:52,  era:4.61, whip:1.10, w:5, l:4 },
  { rank:25, mlbId:702281, name:'Robby Snelling',     pos:'LHP', team:'MIA', age:22, level:'A+/AA',  g:7,  ip:34.0, h:16,  bb:19, so:46,  era:2.38, whip:1.03, w:3, l:2 },
  { rank:26, mlbId:701364, name:'Jamie Arnold',       pos:'RHP', team:'ATH', age:22, level:'AA',     g:11, ip:53.2, h:65,  bb:26, so:57,  era:4.53, whip:1.70, w:2, l:3 },
  { rank:33, mlbId:804636, name:'Jonah Tong',         pos:'RHP', team:'NYM', age:22, level:'A+/AA',  g:12, ip:48.0, h:36,  bb:31, so:62,  era:5.25, whip:1.40, w:2, l:4 },
  { rank:38, mlbId:695611, name:'Gage Jump',          pos:'LHP', team:'ATH', age:23, level:'A+/AA',  g:12, ip:56.1, h:51,  bb:25, so:69,  era:3.83, whip:1.35, w:2, l:3 },
  { rank:46, mlbId:807284, name:'Cam Caminiti',       pos:'RHP', team:'ATL', age:19, level:'A+',     g:10, ip:45.1, h:44,  bb:21, so:44,  era:5.16, whip:1.43, w:1, l:3 },
  { rank:47, mlbId:696146, name:'Hagen Smith',        pos:'LHP', team:'CWS', age:22, level:'AAA',    g:13, ip:47.2, h:31,  bb:33, so:72,  era:3.78, whip:1.34, w:0, l:4 },
  { rank:48, mlbId:803285, name:'Tyler Bremner',      pos:'RHP', team:'LAA', age:22, level:'A+',     g:7,  ip:22.1, h:18,  bb:8,  so:32,  era:1.61, whip:1.16, w:0, l:1 },
  { rank:58, mlbId:702275, name:'JR Ritchie',         pos:'RHP', team:'ATL', age:22, level:'A+/AA',  g:13, ip:65.0, h:47,  bb:36, so:57,  era:3.46, whip:1.28, w:5, l:3 },
  { rank:60, mlbId:695684, name:'Elmer Rodríguez',    pos:'RHP', team:'NYY', age:22, level:'A+/AA',  g:11, ip:52.2, h:47,  bb:28, so:51,  era:3.25, whip:1.42, w:1, l:4 },
  { rank:68, mlbId:805906, name:'Gage Wood',          pos:'RHP', team:'PHI', age:22, level:'A+/AA',  g:11, ip:37.1, h:28,  bb:13, so:54,  era:3.13, whip:1.10, w:0, l:3 },
  { rank:69, mlbId:809254, name:'Anthony Eyanson',    pos:'RHP', team:'BAL', age:21, level:'A+/AA',  g:9,  ip:38.1, h:18,  bb:10, so:53,  era:1.17, whip:0.73, w:2, l:0 },
  { rank:73, mlbId:801739, name:'Carlos Lagrange',    pos:'RHP', team:'NYY', age:23, level:'AAA',    g:12, ip:53.0, h:41,  bb:27, so:70,  era:4.08, whip:1.28, w:1, l:3 },
  { rank:74, mlbId:807291, name:'Caden Scarborough',  pos:'RHP', team:'TEX', age:21, level:'A+/AA',  g:4,  ip:11.0, h:12,  bb:4,  so:10,  era:4.09, whip:1.45, w:0, l:3 },
  { rank:75, mlbId:830402, name:'Kendry Chourio',     pos:'RHP', team:'KC',  age:18, level:'A',      g:10, ip:42.0, h:31,  bb:8,  so:40,  era:1.71, whip:0.93, w:3, l:0 },
  { rank:77, mlbId:689981, name:'River Ryan',         pos:'RHP', team:'DET', age:27, level:'AAA',    g:6,  ip:28.0, h:23,  bb:6,  so:33,  era:2.89, whip:1.04, w:3, l:0 },
  { rank:81, mlbId:811315, name:'Brody Hopkins',      pos:'LHP', team:'TB',  age:24, level:'AAA',    g:12, ip:53.0, h:32,  bb:45, so:62,  era:3.23, whip:1.45, w:1, l:4 },
  { rank:83, mlbId:804817, name:'Kyson Witherspoon',  pos:'RHP', team:'BAL', age:21, level:'A+',     g:10, ip:41.0, h:38,  bb:22, so:42,  era:5.05, whip:1.46, w:1, l:3 },
  { rank:84, mlbId:701388, name:'Jurrangelo Cijntje', pos:'RHP', team:'STL', age:23, level:'AA',     g:11, ip:50.2, h:41,  bb:30, so:64,  era:5.15, whip:1.40, w:3, l:3 },
  { rank:85, mlbId:694393, name:'Jaxon Wiggins',      pos:'LHP', team:'CHC', age:24, level:'AAA',    g:2,  ip:8.0,  h:7,   bb:5,  so:10,  era:5.63, whip:1.50, w:0, l:0 },
  { rank:88, mlbId:687075, name:'Brandon Sproat',     pos:'RHP', team:'MIL', age:24, level:'AAA',    g:13, ip:60.1, h:49,  bb:27, so:70,  era:3.73, whip:1.26, w:4, l:3 },
  { rank:90, mlbId:690986, name:'Kyle Harrison',      pos:'LHP', team:'MIL',  age:24, level:'AAA',    g:12, ip:51.0, h:38,  bb:28, so:68,  era:3.35, whip:1.29, w:3, l:2 },
  { rank:100,mlbId:694357, name:'Ricky Tiedemann',    pos:'LHP', team:'TOR', age:23, level:'AAA',    g:8,  ip:34.2, h:22,  bb:14, so:51,  era:2.34, whip:1.04, w:3, l:1 },
];

export const DRAFT_BOARD = [
  { rank:1,  name:'Roch Cholowsky',   pos:'SS',  school:'UCLA',                          fv:65, risk:'Low',    eta:2027, note:'Best college SS prospect in 20+ years — .320/.452/1.088 as a junior' },
  { rank:2,  name:'Vahn Lackey',      pos:'C',   school:'Georgia Tech',                  fv:65, risk:'Medium', eta:2028, note:'Elite two-way catcher — .397, 20 HR, 15 SB, walked more than he K\'d' },
  { rank:3,  name:'Grady Emerson',    pos:'SS',  school:'Fort Worth Christian HS (TX)', fv:60, risk:'High',   eta:2030, note:'Generational prep bat, earliest and highest ceiling of the class' },
  { rank:4,  name:'Jacob Lombard',    pos:'SS',  school:'Gulliver Prep HS (FL)',         fv:60, risk:'High',   eta:2030, note:'Premium prep SS, one of the top HS bats in the class' },
  { rank:5,  name:'Jackson Flora',    pos:'RHP', school:'UC Santa Barbara',              fv:60, risk:'Low',    eta:2027, note:'Best college arm in class, projects mid-rotation floor with more in tank' },
  { rank:6,  name:'Drew Burress',     pos:'OF',  school:'Georgia Tech',                  fv:55, risk:'Medium', eta:2028, note:'1.130 OPS, elite hit/OBP tools; 5\'9" frame caps some power projection' },
  { rank:7,  name:'Eric Booth Jr.',   pos:'OF',  school:'Oak Grove HS (MS)',             fv:55, risk:'High',   eta:2030, note:'Elite prep bat speed, HR pedigree — MLB.com No. 7 overall prospect' },
  { rank:8,  name:'Cameron Flukey',   pos:'RHP', school:'Coastal Carolina',              fv:55, risk:'Medium', eta:2028, note:'Power arm off a deep-pitching program, missed bats in bunches as a junior' },
  { rank:9,  name:'Tyler Bell',       pos:'SS',  school:'Kentucky',                      fv:55, risk:'Low',    eta:2027, note:'Switch-hitting college SS talent, safe everyday-player floor' },
  { rank:10, name:'Ryder Helfrick',   pos:'C',   school:'Arkansas',                      fv:55, risk:'Medium', eta:2028, note:'Best defensive catcher in the class, arm and receiving both plus' },
];

// Full 2026 Draft-eligible player pool (name + school/status) — a much wider
// net than the ranked Big Board above, meant to be searched/browsed rather
// than graded. "Prep" = high school draftee. No stats/grades are attached
// here since SKIP doesn't have tracked data for most of this pool; that's
// intentional rather than an oversight — see DraftClassPanel.
//
// myRank/actualPick/pickDelta/crowdRank for the top 50 were reconciled against
// MLB_2026_Post_Draft.xlsx (the post-draft analysis workbook) on merge — that
// file is the authoritative source for these four fields going forward.
// crowdRank = public/consensus industry rank for the same name, for comparing
// SKIP's pre-draft board against the crowd once actual picks are known.
export const DRAFT_CLASS_2026 = [
  { name:'Roch Cholowsky', school:'UCLA', pos:'SS', bt:'R/R', myRank:1, score:1, powerRank:1 , actualPick:1, pickDelta:0, crowdRank:1 },
  { name:'Grady Emerson', school:'Prep', pos:'SS', bt:'L/R', myRank:2, score:3, powerRank:3 , actualPick:2, pickDelta:0, crowdRank:3 },
  { name:'Vahn Lackey', school:'Georgia Tech', pos:'C', bt:'R/R', myRank:3, score:2, powerRank:2 , actualPick:3, pickDelta:0, crowdRank:2 },
  { name:'Jackson Flora', school:'UCSB', pos:'RHP', bt:'R/R', myRank:5, score:5, powerRank:5 , actualPick:4, pickDelta:1, crowdRank:4 },
  { name:'Jacob Lombard', school:'Prep', pos:'SS', bt:'R/R', myRank:4, score:7, powerRank:7 , actualPick:14, pickDelta:10, crowdRank:5 },
  { name:'Eric Booth Jr.', school:'Prep', pos:'OF', bt:'R/R', myRank:7, score:7, powerRank:7 , actualPick:7, pickDelta:0, crowdRank:7 },
  { name:'Ryder Helfrick', school:'Arkansas', pos:'C', bt:'R/R', myRank:10, score:11, powerRank:11 , actualPick:15, pickDelta:5, crowdRank:9 },
  { name:'Drew Burress', school:'Georgia Tech', pos:'OF', bt:'R/R', myRank:6, score:7, powerRank:7 , actualPick:8, pickDelta:2, crowdRank:6 },
  { name:'Tyler Bell', school:'Kentucky', pos:'SS', bt:'S/R', myRank:8, score:12, powerRank:12 , actualPick:10, pickDelta:2, crowdRank:8 },
  { name:'Derek Curiel', school:'LSU', pos:'OF', bt:'L/L', myRank:12, score:12, powerRank:12 , actualPick:5, pickDelta:7, crowdRank:11 },
  { name:'Chris Hacopian', school:'Texas A&M', pos:'2B', bt:'R/R', myRank:17, score:15, powerRank:15 , actualPick:11, pickDelta:6, crowdRank:14 },
  { name:'Ace Reese', school:'Mississippi State', pos:'3B', bt:'R/R', myRank:20, score:23, powerRank:23 , actualPick:24, pickDelta:4, crowdRank:19 },
  { name:'Sawyer Strosnider', school:'TCU', pos:'OF', bt:'L/L', myRank:18, score:17, powerRank:17 },
  { name:'A.J. Gracia', school:'Virginia', pos:'OF', bt:'L/L', myRank:21, score:17, powerRank:17 , actualPick:9, pickDelta:12, crowdRank:18 },
  { name:'Cameron Flukey', school:'Coastal Carolina', pos:'RHP', bt:'R/R', myRank:9, score:15, powerRank:14 , actualPick:22, pickDelta:13, crowdRank:10 },
  { name:'Trevor Condon', school:'Prep', pos:'OF', bt:'R/R', myRank:18, score:23, powerRank:23 , actualPick:13, pickDelta:5, crowdRank:20 },
  { name:'Gio Rojas', school:'Prep', pos:'LHP', bt:'L/L', myRank:11, score:15, powerRank:15 , actualPick:16, pickDelta:5, crowdRank:12 },
  { name:'Jared Grindlinger', school:'Prep', pos:'LHP/OF', bt:'L/L', myRank:19, score:15, powerRank:16 , actualPick:12, pickDelta:7, crowdRank:17 },
  { name:'Justin Lebron', school:'Alabama', pos:'SS', bt:'R/R', myRank:14, score:14, powerRank:14 , actualPick:18, pickDelta:4, crowdRank:13 },
  { name:'Liam Peterson', school:'Florida', pos:'RHP', bt:'R/R', myRank:13, score:20, powerRank:20 , actualPick:19, pickDelta:6, crowdRank:16 },
  { name:'Logan Schmidt', school:'Prep', pos:'LHP', bt:'R/R', myRank:34, score:36, powerRank:36 },
  { name:'Tegan Kuhns', school:'Tennessee', pos:'RHP', bt:'R/R', myRank:25, score:27, powerRank:27 , actualPick:32, pickDelta:7, crowdRank:28 },
  { name:'Zion Rose', school:'Louisville', pos:'OF', bt:'R/R', myRank:33, score:35, powerRank:36 , actualPick:6, pickDelta:27, crowdRank:31 },
  { name:'Mason Edwards', school:'USC', pos:'LHP', bt:'L/L', myRank:23, score:27, powerRank:27 , actualPick:47, pickDelta:24, crowdRank:23 },
  { name:'Coleman Borthwick', school:'Prep', pos:'RHP', bt:'R/R', myRank:41, score:38, powerRank:38 , actualPick:21, pickDelta:20, crowdRank:38 },
  { name:'Taylor Rabe', school:'UNC', pos:'RHP', bt:'R/R', myRank:39, score:63, powerRank:61 , actualPick:30, pickDelta:9, crowdRank:49 },
  { name:'Caden Sorrell', school:'Texas A&M', pos:'OF', bt:'L/L', myRank:29, score:39, powerRank:38 },
  { name:'Aiden Robbins', school:'Texas', pos:'OF', bt:'R/R', myRank:25, score:40, powerRank:39 },
  { name:'Cade Townsend', school:'Mississippi', pos:'RHP', bt:'R/R', myRank:26, score:26, powerRank:26 , actualPick:23, pickDelta:3, crowdRank:25 },
  { name:'Tyler Spangler', school:'Prep', pos:'SS', bt:'R/R', myRank:44, score:45, powerRank:45 , actualPick:36, pickDelta:8, crowdRank:43 },
  { name:'Aiden Ruiz', school:'Prep', pos:'SS', bt:'R/R', myRank:43, score:43, powerRank:43 , actualPick:44, pickDelta:1, crowdRank:42 },
  { name:'Jarren Advincula', school:'Georgia Tech', pos:'2B', bt:'R/R', myRank:48, score:49, powerRank:49 , actualPick:45, pickDelta:3, crowdRank:47 },
  { name:'Cole Carlon', school:'ASU', pos:'LHP', bt:'R/R', myRank:28, score:24, powerRank:25 , actualPick:39, pickDelta:11, crowdRank:27 },
  { name:'Hunter Dietz', school:'Arkansas', pos:'LHP', bt:'L/L', myRank:22, score:24, powerRank:23 , actualPick:35, pickDelta:13, crowdRank:21 },
  { name:'Logan Reddemann', school:'UCLA', pos:'RHP', bt:'R/R', myRank:30, score:30, powerRank:30 , actualPick:38, pickDelta:8, crowdRank:30 },
  { name:'Daniel Jackson', school:'Georgia', pos:'C', bt:'R/R', myRank:16, score:37, powerRank:36 , actualPick:37, pickDelta:21, crowdRank:22 },
  { name:'Jack Radel', school:'Notre Dame', pos:'RHP', bt:'R/R', myRank:45, score:44, powerRank:44 , actualPick:28, pickDelta:17, crowdRank:44 },
  { name:'Bo Lowrance', school:'Prep', pos:'3B', bt:'R/R', myRank:24, score:30, powerRank:30 , actualPick:40, pickDelta:16, crowdRank:26 },
  { name:'Cole Prosek', school:'Prep', pos:'C/3B', bt:'R/R', myRank:35, score:42, powerRank:43 , actualPick:41, pickDelta:6, crowdRank:36 },
  { name:'Ben Blair', school:'Liberty', pos:'RHP', bt:'R/R', myRank:51, score:51, powerRank:51 , actualPick:49, pickDelta:2, crowdRank:51 },
  { name:'Blake Bryant', school:'OSU', pos:'RHP', bt:'R/R', myRank:60, score:58, powerRank:58 , actualPick:31, pickDelta:29, crowdRank:60 },
  { name:'Carson Bolemon', school:'Prep', pos:'LHP', bt:'L/L', myRank:26, score:29, powerRank:28 , actualPick:29, pickDelta:3, crowdRank:24 },
  { name:'Jensen Hirschkorn', school:'Prep', pos:'RHP', bt:'R/R', myRank:55, score:58, powerRank:58 },
  { name:'Jack Natili', school:'Cincinnati', pos:'C', bt:'R/R', myRank:58, score:85, powerRank:83 },
  { name:'Carson Tinney', school:'Texas', pos:'C', bt:'R/R', myRank:67, score:73, powerRank:72 , actualPick:43, pickDelta:24, crowdRank:66 },
  { name:'Logan Hughes', school:'Texas Tech', pos:'OF', bt:'R/R', myRank:42, score:40, powerRank:40 , actualPick:17, pickDelta:25, crowdRank:40 },
  { name:'Beau Peterson', school:'Prep', pos:'3B', bt:'R/R', myRank:63, score:77, powerRank:76 },
  { name:'Chase Brunson', school:'TCU', pos:'OF', bt:'R/R', myRank:38, score:39, powerRank:39 , actualPick:42, pickDelta:4, crowdRank:37 },
  { name:'Andrew Williamson', school:'Central Florida', pos:'OF', bt:'R/R', myRank:77, score:70, powerRank:71 },
  { name:'Chris Rembert', school:'Auburn', pos:'2B/OF', bt:'L/L', myRank:41, score:43, powerRank:43 },
  { name:'Eric Becker', school:'Virginia', pos:'SS', bt:'L/R', myRank:32, score:31, powerRank:31 },
  { name:'Archer Horn', school:'Prep', pos:'SS', bt:'R/R', myRank:52, score:48, powerRank:48 },
  { name:'Ruger Riojas', school:'Texas', pos:'RHP', bt:'R/R', myRank:62, score:77, powerRank:76 },
  { name:'Jake Brown', school:'LSU', pos:'OF', bt:'L/L', myRank:53, score:56, powerRank:56 },
  { name:'Ty Head', school:'NC State', pos:'OF', bt:'R/R', myRank:59, score:57, powerRank:57 , actualPick:46, pickDelta:13, crowdRank:59 },
  { name:'Tre Broussard', school:'Houston', pos:'OF', bt:'R/R', myRank:44, score:83, powerRank:80 },
  { name:'Connor Comeau', school:'Prep', pos:'SS/3B', bt:'R/R', myRank:60, score:56, powerRank:56 },
  { name:'Joseph Contreras', school:'Prep', pos:'RHP', bt:'R/R', myRank:43, score:55, powerRank:55 },
  { name:'Cooper Harris', school:'Community College', pos:'RHP', bt:'R/R', myRank:68, score:65, powerRank:65 },
  { name:'Landon Thome', school:'Prep', pos:'1B', bt:'L/L', myRank:46, score:48, powerRank:47 , actualPick:34, pickDelta:12, crowdRank:45 },
  { name:'Landon Brown', school:'Prep', pos:'RHP', bt:'R/R', myRank:69, score:79, powerRank:78 },
  { name:'Noah Wilson', school:'Prep', pos:'OF', bt:'R/R', myRank:96, score:88, powerRank:88 },
  { name:'Ethan Kleinschmit', school:'OSU', pos:'LHP', bt:'R/R', myRank:70, score:81, powerRank:80 },
  { name:'Savion Sims', school:'Prep', pos:'RHP', bt:'R/R', myRank:84, score:83, powerRank:83 },
  { name:'Carson Bailey', school:'Community College', pos:'LHP', bt:'R/R', myRank:71, score:85, powerRank:84 },
  { name:'Owen Hull', school:'UNC', pos:'OF', myRank:161, score:138, powerRank:140 },
  { name:'Jacob Dudan', school:'NC State', pos:'RHP', bt:'R/R', myRank:72, score:68, powerRank:68 },
  { name:'Will Brick', school:'Prep', pos:'C', bt:'R/R', myRank:54, score:57, powerRank:57 },
  { name:'Kaden Waechter', school:'Prep', pos:'RHP', bt:'R/R', myRank:56, score:52, powerRank:53 },
  { name:'Gavin Grahovac', school:'Texas A&M', pos:'1B/3B', bt:'R/R', myRank:37, score:58, powerRank:56 },
  { name:'Brody Bumila', school:'Prep', pos:'LHP', bt:'L/L', myRank:24, score:38, powerRank:37 },
  { name:'Wes Mendes', school:'Florida State', pos:'LHP', bt:'L/L', myRank:64, score:60, powerRank:60 },
  { name:'Taj Marchand', school:'Prep', pos:'SS', bt:'R/R', myRank:47, score:46, powerRank:45 , actualPick:33, pickDelta:14, crowdRank:46 },
  { name:'Ethan Bass', school:'Prep', pos:'SS', bt:'R/R', myRank:74, score:80, powerRank:80 },
  { name:'Sean Duncan', school:'Prep', pos:'OF', bt:'L/L', myRank:48, score:52, powerRank:52 },
  { name:'Denton Lord', school:'Prep', pos:'RHP', bt:'R/R', myRank:75, score:88, powerRank:87 },
  { name:'Brett Renfrow', school:'Virginia Tech', pos:'RHP', bt:'R/R', myRank:105, score:135, powerRank:133 },
  { name:'Rocco Maniscalco', school:'Prep', pos:'SS', bt:'R/R', myRank:31, score:67, powerRank:68 , actualPick:50, pickDelta:19, crowdRank:41 },
  { name:'Carter Beck', school:'Prep', pos:'OF', myRank:130, score:144, powerRank:141 , actualPick:26, pickDelta:104, crowdRank:134 },
  { name:'Blake Bowen', school:'Prep', pos:'OF', bt:'R/R', myRank:73, score:62, powerRank:63 },
  { name:'Caden Bogenpohl', school:'Missouri State', pos:'OF', bt:'R/R', myRank:78, score:84, powerRank:84 },
  { name:'Kyle Jones', school:'Florida', pos:'OF', bt:'R/R', myRank:79, score:94, powerRank:93 },
  { name:'Dee Kennedy', school:'Kansas State', pos:'SS', bt:'R/R', myRank:80, score:84, powerRank:84 },
  { name:'Cole Koeninger', school:'Prep', pos:'RHP', bt:'R/R', myRank:98, score:87, powerRank:88 },
  { name:'Peyton Bonds', school:'Rutgers', pos:'OF', bt:'R/R', myRank:81, score:87, powerRank:86 },
  { name:'Tommy LaPour', school:'TCU', pos:'RHP', myRank:155, score:140, powerRank:141 },
  { name:'Bo Holloway', school:'Nolensville', pos:'LHP', bt:'R/R', myRank:82, score:84, powerRank:84 },
  { name:'Garrett Wright', school:'Tennessee', pos:'OF/C', myRank:191, score:169, powerRank:171 },
  { name:'Ryan Peterson', school:'Sam Houston', pos:'RHP', bt:'R/R', myRank:85, score:87, powerRank:87 },
  { name:'Kaiden McCarthy', school:'Prep', pos:'RHP', bt:'R/R', myRank:82, score:83, powerRank:84 , actualPick:48, pickDelta:34, crowdRank:82 },
  { name:'Ethan Wachsmann', school:'Prep', pos:'RHP', bt:'R/R', myRank:88, score:73, powerRank:74 },
  { name:'Shawn Sullivan', school:'Prep', pos:'RHP', bt:'R/R', myRank:89, score:96, powerRank:96 },
  { name:'Carson Wiggins', school:'Arkansas', pos:'RHP', bt:'R/R', myRank:87, score:85, powerRank:85 , actualPick:27, pickDelta:60, crowdRank:86 },
  { name:'Shane Sdao', school:'Texas A&M', pos:'LHP', bt:'R/R', myRank:92, score:95, powerRank:95 },
  { name:'Joey Volchko', school:'Georgia', pos:'RHP', bt:'R/R', myRank:65, score:69, powerRank:69 },
  { name:'Gabe Gaeckle', school:'Arkansas', pos:'RHP', bt:'R/R', myRank:93, score:90, powerRank:90 },
  { name:'Ryan Lynch', school:'UNC', pos:'RHP', bt:'R/R', myRank:94, score:93, powerRank:93 },
  { name:'Cooper Sides', school:'Prep', pos:'RHP', bt:'R/R', myRank:99, score:100, powerRank:100 },
  { name:'Evan Dempsey', school:'FGC', pos:'RHP/OF', bt:'R/R', myRank:100, score:100, powerRank:100 },
  { name:'Anthony Murphy', school:'Prep', pos:'OF', bt:'R/R', myRank:101, score:104, powerRank:103 },
  { name:'Mulivai Levu', school:'UCLA', pos:'1B', bt:'R/R', myRank:97, score:91, powerRank:91 },
  { name:'Wilson Andersen', school:'Prep', pos:'RHP', bt:'R/R', myRank:102, score:105, powerRank:104 },
  { name:'Myles Bailey', school:'Oklahoma State', pos:'1B', bt:'R/R', myRank:103, score:98, powerRank:98 },
  { name:'Brendan Brock', school:'Oklahoma', pos:'C/OF', bt:'R/R', myRank:104, score:110, powerRank:109 },
  { name:'Hudson DeVaughan', school:'Prep', pos:'RHP', bt:'R/R', myRank:107, score:109, powerRank:109 },
  { name:'Will Gasparino', school:'UCLA', pos:'OF', bt:'R/R', myRank:108, score:91, powerRank:92 },
  { name:'Will Adams', school:'Prep', pos:'OF/1B', bt:'R/R', myRank:112, score:105, powerRank:105 },
  { name:'Caden Ferraro', school:'Texas Tech', pos:'OF', bt:'L/L', myRank:95, score:111, powerRank:110 },
  { name:"James Clark", school:"St. John's", pos:'SS', bt:'L/R', myRank:61, score:69, powerRank:68 },
  { name:'Camden Kozeal', school:'Arkansas', pos:'SS/2B', bt:'L/R', myRank:90, score:113, powerRank:112 },
  { name:'Jake Schaffner', school:'Prep', pos:'SS', myRank:97, score:96, powerRank:97 , actualPick:20, pickDelta:77, crowdRank:94 },
  { name:'Kollin Ritchie', school:'Mississippi', pos:'OF', myRank:109, score:105, powerRank:105 },
  { name:'Jack Slightom', school:'Prep', pos:'RHP', myRank:111, score:105, powerRank:105 },
  { name:'Luke Williams', school:'Prep', pos:'SS', bt:'R/R', myRank:87, score:102, powerRank:101 },
  { name:'Keon Johnson', school:'Prep', pos:'SS', myRank:120, score:114, powerRank:114 },
  { name:'Will Yow', school:'Prep', pos:'SS', myRank:113, score:102, powerRank:102 },
  { name:'Kevin Roberts Jr.', school:'Prep', pos:'OF', bt:'R/R', myRank:132, score:114, powerRank:116 },
  { name:'Kade Lewis', school:'Wake Forest', pos:'1B', myRank:114, score:118, powerRank:118 },
  { name:'Daniel Cuvet', school:'Miami', pos:'3B', myRank:121, score:111, powerRank:112 },
  { name:'Dylan Bowen', school:'Prep', pos:'SS', myRank:115, score:113, powerRank:113 },
  { name:'Jack Dugan', school:'Prep', pos:'SS/3B', myRank:116, score:120, powerRank:119 },
  { name:'Trey Ebel', school:'Prep', pos:'SS', myRank:113, score:114, powerRank:114 , actualPick:25, pickDelta:88, crowdRank:114 },
  { name:'Malachi Washington', school:'Prep', pos:'OF', myRank:117, score:119, powerRank:119 },
  { name:'Roman Martin', school:'UCLA', pos:'LHP', bt:'R/R', myRank:83, score:98, powerRank:97 },
  { name:'Saen Dunlap', school:'Prep', pos:'C', myRank:118, score:127, powerRank:126 },
  { name:'Tre Phelps', school:'Georgia', pos:'3B', bt:'R/R', myRank:122, score:129, powerRank:128 },
  { name:'Julian Garcia', school:'Prep', pos:'RHP', myRank:123, score:124, powerRank:124 },
  { name:'Gavin Giese', school:'Prep', pos:'RHP', myRank:124, score:123, powerRank:123 },
  { name:'Breyy Renfrow', school:'Virginia Tech', pos:'RHP', myRank:125, score:132, powerRank:131 },
  { name:'Kolby Stringerr', school:'Prep', pos:'RHP', myRank:126, score:133, powerRank:132 },
  { name:'AJ Rice', school:'Prep', pos:'RHP', myRank:127, score:129, powerRank:129 },
  { name:'Logan Georges', school:'Prep', pos:'RHP', myRank:128, score:135, powerRank:135 },
  { name:'Carson Kerce', school:'Georgia Tech', pos:'SS', myRank:135, score:115, powerRank:116 },
  { name:'Josiah Morris', school:'Prep', pos:'SS', myRank:129, score:125, powerRank:125 },
  { name:'Jason DeCaro', school:'North Carolina', pos:'RHP', myRank:130, score:124, powerRank:124 },
  { name:'Trey Beard', school:'Florida State', pos:'LHP', myRank:131, score:131, powerRank:131 },
  { name:'Camden Johnson', school:'Oklahoma', pos:'3B', myRank:133, score:134, powerRank:134 },
  { name:'Tyson LeBlanc', school:'Kansas', pos:'SS', myRank:134, score:137, powerRank:137 },
  { name:'Ryan Cooney', school:'Oregon', pos:'2B', myRank:136, score:142, powerRank:142 },
  { name:'Tyler Putnam', school:'Prep', pos:'RHP', myRank:137, score:123, powerRank:124 },
  { name:'Dominic Santarelli', school:'Prep', pos:'1B', myRank:138, score:135, powerRank:135 },
  { name:'Alex Weingartner', school:'Prep', pos:'OF', myRank:159, score:136, powerRank:138 },
  { name:'Steele Murdock', school:'UCSD', pos:'RHP', myRank:139, score:139, powerRank:139 },
  { name:'Brady Harris', school:'Prep', pos:'OF', myRank:163, score:147, powerRank:148 },
  { name:'Elliot Lascelles', school:'Prep', pos:'SS', myRank:158, score:139, powerRank:141 },
  { name:'Gary Morse', school:'Prep', pos:'RHP', myRank:140, score:148, powerRank:147 },
  { name:'Nathaneal Davis', school:'Prep', pos:'OF', myRank:141, score:141, powerRank:141 },
  { name:'Graham Schlicht', school:'Prep', pos:'RHP', myRank:142, score:147, powerRank:146 },
  { name:'Ethan McElvain', school:'Arkansas', pos:'LHP', myRank:143, score:151, powerRank:150 },
  { name:'Deven Sheerin', school:'LSU', pos:'RHP', myRank:144, score:146, powerRank:146 },
  { name:'Dalton Wentz', school:'Wake Forest', pos:'3B/2B', myRank:145, score:143, powerRank:144 },
  { name:'Alex Hernandez', school:'Georgia Tech', pos:'OF/1B', myRank:146, score:152, powerRank:151 },
  { name:'Joe Tiroly', school:'Virginia', pos:'2B/3B', myRank:147, score:154, powerRank:154 },
  { name:'Henry Ford', school:'Tennessee', pos:'3B', myRank:148, score:147, powerRank:147 },
  { name:'Ethan Norby', school:'East Carolina', pos:'LHP', bt:'L/L', myRank:167, score:139, powerRank:141 },
  { name:'Jaxon Willits', school:'Oklahoma', pos:'SS', myRank:149, score:149, powerRank:149 },
  { name:'Ryan Marohn', school:'NC State', pos:'LHP', myRank:150, score:151, powerRank:151 },
  { name:'Kyle Johnson', school:'Virginia', pos:'LHP', myRank:151, score:143, powerRank:143 },
  { name:'CJ Weinstein', school:'Prep', pos:'SS', myRank:152, score:153, powerRank:153 },
  { name:'Jake McCoy', school:'South Carolina', pos:'LHP', myRank:153, score:152, powerRank:152 },
  { name:'Lucas Nawrocki', school:'Prep', pos:'LHP', myRank:154, score:155, powerRank:155 },
  { name:'Trey Rangel', school:'Prep', pos:'RHP', myRank:156, score:163, powerRank:162 },
  { name:'Bryce Hill', school:'Prep', pos:'RHP', myRank:157, score:157, powerRank:157 },
  { name:'Jason Amalbert', school:'Prep', pos:'RHP', myRank:160, score:159, powerRank:159 },
  { name:'Kyle Casteel', school:'Prep', pos:'RHP', myRank:162, score:166, powerRank:166 },
  { name:'Alex Sosa', school:'Miami', pos:'C', myRank:164, score:168, powerRank:168 },
  { name:'Jaxon Jelkin', school:'Kentucky', pos:'RHP', myRank:165, score:169, powerRank:169 },
  { name:'Isaac Morton', school:'Minnesota', pos:'RHP', myRank:166, score:170, powerRank:170 },
  { name:'James Jorgensen', school:'Prep', pos:'RHP', myRank:168, score:172, powerRank:172 },
  { name:'Cameron Johnson', school:'Oklahoma', pos:'LHP', myRank:169, score:161, powerRank:162 },
  { name:'Dawson Montesa', school:'West Virginia', pos:'RHP', myRank:170, score:158, powerRank:159 },
  { name:'Brady Snow', school:'Prep', pos:'RHP', myRank:171, score:173, powerRank:173 },
  { name:'James Tronstein', school:'Prep', pos:'OF/SS', myRank:172, score:164, powerRank:165 },
  { name:'Jacob Madrid', school:'Prep', pos:'C', myRank:173, score:176, powerRank:176 },
  { name:'Grayson Willoughby', school:'Prep', pos:'RHP', myRank:199, score:176, powerRank:177 },
  { name:'Carson Jasa', school:'Nebraska', pos:'RHP', myRank:174, score:162, powerRank:163 },
  { name:'LJ Mercurius', school:'Oklahoma', pos:'RHP', myRank:175, score:179, powerRank:178 },
  { name:'Maddox Molony', school:'Oregon', pos:'SS', myRank:176, score:180, powerRank:179 },
  { name:'Owen Kramkowski', school:'Arizona', pos:'RHP', myRank:177, score:174, powerRank:174 },
  { name:'Russell Sandefer', school:'Florida', pos:'RHP', myRank:178, score:182, powerRank:181 },
  { name:'Brayden Dowd', school:'Florida State', pos:'OF', myRank:179, score:180, powerRank:180 },
  { name:'Trevor Hansen', school:'UC Irvine', pos:'RHP', myRank:180, score:184, powerRank:183 },
  { name:'Coleton Brady', school:'Prep', pos:'RHP', myRank:181, score:176, powerRank:176 },
  { name:'Wil Libbert', school:'Mississippi', pos:'LHP', myRank:182, score:186, powerRank:185 },
  { name:'Kaleb LaFavor', school:'Prep', pos:'RHP', myRank:183, score:187, powerRank:187 },
  { name:'Landon Thiel', school:'Prep', pos:'LHP', myRank:184, score:188, powerRank:188 },
  { name:'Jason Jutronich', school:'Prep', pos:'LHP', myRank:185, score:189, powerRank:189 },
  { name:'Luke McNeillie', school:'Florida', pos:'RHP', myRank:186, score:190, powerRank:190 },
  { name:'Genson Veras', school:'Prep', pos:'OF', myRank:187, score:184, powerRank:184 },
  { name:'Sawyer Nelson', school:'Prep', pos:'SS', myRank:188, score:189, powerRank:189 },
  { name:'Robbie Lavey', school:'Prep', pos:'C', bt:'R/R', myRank:189, score:172, powerRank:173 },
  { name:'Rylan Lujo', school:'Georgia', pos:'OF', myRank:190, score:190, powerRank:190 },
  { name:'Jet Berry', school:'Prep', pos:'SS', myRank:192, score:192, powerRank:192 },
  { name:'Cal Scolari', school:'Oregon', pos:'RHP', myRank:193, score:197, powerRank:197 },
  { name:'Duncan Marsten', school:'Wake Forest', pos:'RHP', myRank:194, score:193, powerRank:193 },
  { name:'Martin Shelar', school:'Prep', pos:'OF', myRank:195, score:187, powerRank:188 },
  { name:'Spencer Evans', school:'Prep', pos:'LHP', myRank:196, score:200, powerRank:200 },
  { name:'Ryne Barker', school:'Prep', pos:'SS/3B', myRank:197, score:197, powerRank:197 },
  { name:'Will Plunkett', school:'Prep', pos:'SS', myRank:198, score:196, powerRank:196 },
  { name:'Gavin Gallaher', school:'UNC', pos:'2B', myRank:200, score:194, powerRank:195 },
  { name:'Dylan Vigue', school:'Georgia', pos:'RHP', myRank:201, score:198, powerRank:198 },
  { name:'Jorvorskie Lane Jr.', school:'Prep', pos:'OF', myRank:202, score:205, powerRank:205 },
  { name:'Sean Dunlap', school:'Prep', pos:'C', bt:'R/R', myRank:204, score:188, powerRank:189 },
  { name:'Aidan Knaak', school:'Clemson', pos:'RHP', bt:'R/R', myRank:203, score:187, powerRank:188 },
  { name:'Jace Mataczynski', school:'Prep', pos:'SS', myRank:206, score:178, powerRank:180 },
  { name:'Braden Holcomb', school:'Vanderbilt', pos:'OF/3B', bt:'R/R', myRank:205, score:195, powerRank:196 },
  { name:'Jon Mora', school:'Prep', pos:'OF', bt:'L/R', myRank:207, score:197, powerRank:198 },
  { name:'Nathan Taylor', school:'Cincinnati', pos:'SS', bt:'R/R', myRank:208, score:193, powerRank:194 },
  { name:'Chase Kiker', school:'Prep', pos:'RHP', bt:'R/R', myRank:209, score:200, powerRank:201 },
  { name:'Maxx Yehl', school:'West Virginia', pos:'LHP', bt:'L/L', myRank:210, score:191, powerRank:192 },
];

export const LEAGUE_TRENDS = [
  { metric:'Home Run Rate',       value:'+6.8%',    up:true  },
  { metric:'Avg Exit Velocity',   value:'89.8 mph', up:true  },
  { metric:'Strikeout Rate',      value:'-1.9%',    up:false },
  { metric:'Walk Rate',           value:'+0.8%',    up:true  },
  { metric:'Avg Fastball Velo',   value:'94.1 mph', up:true  },
  { metric:'Barrel %',            value:'9.2%',     up:true  },
];

export const INJURIES = [
  { severity:'Low / Day-to-Day', count:18, color:C.teal  },
  { severity:'15-Day IL',        count:12, color:C.amber },
  { severity:'60-Day IL',        count:7,  color:C.rust  },
  { severity:'60-Day+ IL',       count:3,  color:'#8B2020' },
];

export const FARM_GRADES = [
  { team:'SEA', grade:'A+', count:7, color:C.teal  },
  { team:'PIT', grade:'A+', count:5, color:C.teal  },
  { team:'CLE', grade:'A',  count:6, color:C.amber },
  { team:'MIL', grade:'A',  count:5, color:C.amber },
  { team:'DET', grade:'A-', count:5, color:C.amber },
  { team:'STL', grade:'B+', count:5, color:C.slate },
  { team:'LAD', grade:'B+', count:5, color:C.slate },
  { team:'MIA', grade:'B',  count:5, color:C.slate },
];

// Real in-season trades involving high-end starting pitchers (Roadmap #5).
// Transcribed from a Freylitics (@RobertFrey40) reference chart the user
// shared — these are real transactions involving real players, so unlike
// most of this file's other static arrays, nothing here is invented or
// stat-projected. netWar is shown from the perspective of the team trading
// AWAY the headliner (matching the source chart's framing exactly): a
// positive number means the trading-away team's return outproduced what
// the headliner gave the acquiring team from the trade date forward; a
// negative number means the acquiring team won the deal.
export const NOTABLE_TRADES = [
  { date:'2015-07-30', fromTeam:'DET', toTeam:'TOR', headliner:'David Price',
    sent:['LHP David Price'],
    received:['LHP Matt Boyd','LHP Daniel Norris','LHP Jairo Labourt'], netWar:13.6 },
  { date:'2022-08-01', fromTeam:'ATH', toTeam:'NYY', headliner:'Frankie Montas',
    sent:['RHP Frankie Montas','RHP Lou Trivino'],
    received:['LHP JP Sears','LHP Ken Waldichuk','RHP Luis Medina','2B Cooper Bowman'], netWar:7.7 },
  { date:'2017-07-31', fromTeam:'ATH', toTeam:'NYY', headliner:'Sonny Gray',
    sent:['RHP Sonny Gray','Future Considerations'],
    received:['CF Dustin Fowler','RHP James Kaprielian','SS Jorge Mateo'], netWar:0.3 },
  { date:'2014-07-31', fromTeam:'BOS', toTeam:'ATH', headliner:'Jon Lester',
    sent:['LHP Jon Lester','LF Jonny Gomes','Cash'],
    received:['LF Yoenis Cespedes'], netWar:0.2 },
  { date:'2015-07-26', fromTeam:'CIN', toTeam:'KC', headliner:'Johnny Cueto',
    sent:['RHP Johnny Cueto','Cash'],
    received:['LHP Brandon Finnegan','LHP Cody Reed','LHP John Lamb'], netWar:-1.4 },
  { date:'2021-07-30', fromTeam:'WSH', toTeam:'LAD', headliner:'Max Scherzer',
    sent:['RHP Max Scherzer','SS Trea Turner'],
    received:['C Keibert Ruiz','RHP Josiah Gray','RHP Gerardo Carrillo','OF Donovan Casey'], netWar:-1.5 },
  { date:'2017-07-31', fromTeam:'TEX', toTeam:'LAD', headliner:'Yu Darvish',
    sent:['RHP Yu Darvish'],
    received:['2B Willie Calhoun','RHP A.J. Alexy','SS Brendon Davis'], netWar:-2.4 },
  { date:'2019-07-31', fromTeam:'ARI', toTeam:'HOU', headliner:'Zack Greinke',
    sent:['RHP Zack Greinke','Cash'],
    received:['RHP Corbin Martin','RHP J.B. Bukauskas','3B Josh Rojas','LF Seth Beer'], netWar:-2.6 },
  { date:'2015-07-31', fromTeam:'PHI', toTeam:'TEX', headliner:'Cole Hamels',
    sent:['LHP Cole Hamels','LHP Jake Diekman','Cash'],
    received:['LHP Matt Harrison','C Jorge Alfaro','RHP Jerad Eickhoff','OF Nick Williams','RHP Alec Asher','RHP Jake Thompson'], netWar:-8.3 },
  { date:'2017-08-31', fromTeam:'DET', toTeam:'HOU', headliner:'Justin Verlander',
    sent:['RHP Justin Verlander','Cash','Player To Be Named Later'],
    received:['CF Daz Cameron','RHP Franklin Perez','C Jake Rogers'], netWar:-19.7 },
];

export const RUN_DIFF_DATA = Array.from({ length:20 }, (_,i) => ({
  game: i+1,
  diff: [3,-1,2,-2,4,1,-1,3,2,-1,5,-2,1,4,-1,2,3,-2,4,2][i],
  cum:  0,
})).map((d,i,arr) => ({ ...d, cum: arr.slice(0,i+1).reduce((s,x)=>s+x.diff, 0) }));

export const PARITY_GAUGE = [
  { name:'competitive', value:72, fill:C.amber   },
  { name:'rest',        value:28, fill:C.surface3 },
];

export const BATTING_LEADERS = [
  { rank:1,  name:'Shohei Ohtani',     team:'LAD', pos:'DH',  pa:509, avg:.292, obp:.393, slg:.544, ops:.937, woba:.412, xwoba:.405, ev:94.8, hh:56.5, brl:18.2, xba:.289, xslg:.538, bbPct:13.6, kPct:23.0, war:6.4 },
  { rank:2,  name:'Aaron Judge',       team:'NYY', pos:'RF',  pa:341, avg:.298, obp:.415, slg:.622, ops:1.037, woba:.448, xwoba:.468, ev:95.1, hh:61.8, brl:21.4, xba:.304, xslg:.672, bbPct:18.2, kPct:24.1, war:5.5 },
  { rank:3,  name:'Freddie Freeman',   team:'LAD', pos:'1B',  pa:348, avg:.318, obp:.404, slg:.528, ops:.932,  woba:.411, xwoba:.396, ev:89.4, hh:44.8, brl:10.9, xba:.283, xslg:.490, bbPct:13.2, kPct:15.6, war:4.9 },
  { rank:4,  name:'Juan Soto',         team:'NYM', pos:'RF',  pa:362, avg:.294, obp:.421, slg:.504, ops:.925,  woba:.412, xwoba:.408, ev:90.6, hh:47.1, brl:13.2, xba:.279, xslg:.491, bbPct:17.8, kPct:16.8, war:4.8 },
  { rank:5,  name:'Gunnar Henderson',  team:'BAL', pos:'SS',  pa:336, avg:.278, obp:.358, slg:.528, ops:.886,  woba:.399, xwoba:.403, ev:91.8, hh:51.8, brl:15.4, xba:.286, xslg:.541, bbPct:10.4, kPct:22.1, war:4.7 },
  { rank:6,  name:'Bobby Witt Jr.',    team:'KC',  pos:'SS',  pa:358, avg:.302, obp:.361, slg:.514, ops:.875,  woba:.391, xwoba:.389, ev:91.2, hh:50.8, brl:13.8, xba:.299, xslg:.518, bbPct:8.1,  kPct:18.4, war:4.6 },
  { rank:7,  name:'Mookie Betts',      team:'LAD', pos:'SS',  pa:329, avg:.291, obp:.374, slg:.498, ops:.872,  woba:.388, xwoba:.381, ev:89.1, hh:45.2, brl:11.4, xba:.278, xslg:.482, bbPct:12.2, kPct:15.2, war:4.4 },
  { rank:8,  name:'Yordan Alvarez',    team:'HOU', pos:'DH',  pa:314, avg:.286, obp:.368, slg:.504, ops:.872,  woba:.389, xwoba:.394, ev:93.4, hh:58.2, brl:19.1, xba:.294, xslg:.542, bbPct:13.8, kPct:16.9, war:4.1 },
  { rank:9,  name:'Jose Ramirez',      team:'CLE', pos:'3B',  pa:344, avg:.278, obp:.354, slg:.500, ops:.854,  woba:.382, xwoba:.376, ev:90.1, hh:46.8, brl:12.2, xba:.272, xslg:.478, bbPct:11.2, kPct:14.1, war:4.2 },
  { rank:10, name:'Corey Seager',      team:'TEX', pos:'SS',  pa:298, avg:.284, obp:.362, slg:.494, ops:.856,  woba:.381, xwoba:.378, ev:89.8, hh:44.2, brl:11.8, xba:.276, xslg:.481, bbPct:12.0, kPct:18.2, war:3.9 },
  { rank:11, name:'Rafael Devers',     team:'BOS', pos:'3B',  pa:332, avg:.279, obp:.342, slg:.504, ops:.846,  woba:.378, xwoba:.381, ev:90.8, hh:48.1, brl:13.6, xba:.281, xslg:.514, bbPct:9.4,  kPct:19.8, war:3.8 },
  { rank:12, name:'Paul Goldschmidt',  team:'NYY', pos:'1B',  pa:318, avg:.276, obp:.358, slg:.486, ops:.844,  woba:.376, xwoba:.371, ev:88.4, hh:42.8, brl:10.4, xba:.270, xslg:.472, bbPct:12.8, kPct:21.4, war:3.6 },
  { rank:13, name:'Luis Arraez',       team:'MIA', pos:'2B',  pa:368, avg:.344, obp:.399, slg:.441, ops:.840,  woba:.372, xwoba:.362, ev:83.8, hh:28.4, brl:3.8,  xba:.334, xslg:.428, bbPct:8.8,  kPct:5.8,  war:3.5 },
  { rank:14, name:'Ronald Acuña Jr.',  team:'ATL', pos:'OF',  pa:322, avg:.296, obp:.378, slg:.498, ops:.876,  woba:.392, xwoba:.388, ev:90.2, hh:46.4, brl:12.8, xba:.288, xslg:.491, bbPct:11.8, kPct:19.6, war:4.3 },
  { rank:15, name:'Kyle Tucker',       team:'HOU', pos:'RF',  pa:338, avg:.288, obp:.362, slg:.491, ops:.853,  woba:.382, xwoba:.379, ev:89.6, hh:43.8, brl:11.2, xba:.280, xslg:.476, bbPct:12.1, kPct:18.9, war:3.8 },
];

export const PITCHING_LEADERS = [
  { rank:1,  name:'Spencer Strider',      team:'ATL', h:'R', gs:18, ip:114.2, era:2.14, fip:2.08, whip:0.88, k9:14.8, bb9:2.1, hr9:0.62, kBB:7.04, war:4.8 },
  { rank:2,  name:'Gerrit Cole',          team:'NYY', h:'R', gs:18, ip:118.1, era:2.44, fip:2.31, whip:0.94, k9:12.1, bb9:1.8, hr9:0.68, kBB:6.72, war:4.4 },
  { rank:3,  name:'Yoshinobu Yamamoto',   team:'LAD', h:'R', gs:17, ip:111.0, era:2.58, fip:2.41, whip:0.96, k9:11.8, bb9:2.0, hr9:0.73, kBB:5.90, war:4.1 },
  { rank:4,  name:'Tyler Glasnow',        team:'LAD', h:'R', gs:16, ip:104.2, era:2.68, fip:2.52, whip:0.98, k9:12.4, bb9:2.4, hr9:0.69, kBB:5.17, war:3.9 },
  { rank:5,  name:'Tarik Skubal',         team:'DET', h:'L', gs:17, ip:108.1, era:2.74, fip:2.61, whip:1.00, k9:11.2, bb9:1.9, hr9:0.75, kBB:5.89, war:3.8 },
  { rank:6,  name:'Zack Wheeler',         team:'PHI', h:'R', gs:17, ip:112.0, era:2.88, fip:2.74, whip:1.02, k9:10.4, bb9:2.1, hr9:0.72, kBB:4.95, war:3.7 },
  { rank:7,  name:'Dylan Cease',          team:'SD',  h:'R', gs:16, ip:101.1, era:2.94, fip:2.81, whip:1.04, k9:11.8, bb9:3.1, hr9:0.71, kBB:3.81, war:3.5 },
  { rank:8,  name:'Corbin Burnes',        team:'BAL', h:'R', gs:17, ip:110.2, era:3.02, fip:2.88, whip:1.06, k9:10.8, bb9:1.8, hr9:0.73, kBB:6.00, war:3.6 },
  { rank:9,  name:'Blake Snell',          team:'SF',  h:'L', gs:15, ip:96.0,  era:3.08, fip:2.94, whip:1.08, k9:12.0, bb9:3.8, hr9:0.66, kBB:3.16, war:3.2 },
  { rank:10, name:'Kevin Gausman',        team:'TOR', h:'R', gs:16, ip:104.0, era:3.14, fip:3.02, whip:1.09, k9:10.2, bb9:2.2, hr9:0.78, kBB:4.64, war:3.1 },
];

export const GAME_THEORY = {
  definitions: { nashEquilibrium:"A stable state where no player can improve their outcome by unilaterally changing strategy, given all other players' strategies are fixed.", dominantStrategy:"A strategy that produces the best outcome for a player regardless of what other players choose.", zeroSum:"A game where one player's gain exactly equals another's loss — total payoff is constant.", nonZeroSum:"A game where the combined payoffs can increase or decrease — cooperation can create mutual gain.", signalingGame:"A game where one player (the sender) has private information and the other (receiver) must interpret signals to infer it.", mixedStrategy:"A player randomizes over possible strategies to prevent opponents from exploiting a predictable pattern." },
  countStrategies: { count30:{ label:"3-0 Count", pitcherNE:"Throw fastball — maximizes strike probability, avoids walk, avoids favorable hitter's count deepening.", hitterNE:"Sit on fastball — highest probability pitch, maximize damage opportunity.", insight:"3-0 is the most pitcher-disadvantaged count. Both sides know a fastball is coming. The NE is: pitcher throws fastball, hitter swings — yet 'take' signs still dominate. This is a deviation from Nash driven by organizational heuristics and risk aversion." }, count32:{ label:"3-2 Count", pitcherNE:"Mixed strategy: off-speed to disrupt timing, but fastball if command is uncertain.", hitterNE:"Expand zone awareness — must protect plate, cannot take borderline pitches.", insight:"3-2 forces both sides into mixed strategies. Optimal pitcher strategy is randomized between fastball and secondary. Hitters who can identify pitch type early gain massive EV advantage. This is the count where pitch tunneling matters most." }, countGeneral:{ fastballUsage:"Fastball usage declines monotonically as strike count increases — pitchers shift to off-speed to induce weak contact and generate swings on pitches outside the zone.", battersWithTwoStrikes:"Zone expansion is the empirically dominant hitter strategy with two strikes — contact rate matters more than power, so hitters must expand to avoid strikeouts.", insight:"Swartz (SABR 2013): 'Pitchers in hitter's counts should throw more fastballs, in pitcher's counts more off-speed.' The mixed strategy NE in high leverage counts is the least exploited edge in player evaluation." } },
  inGameGames: { pitcherSwitching:{ structure:"Manager (player A) vs opposing hitter (player B). Manager chooses LHP/RHP; hitter has L/R platoon advantage. Simultaneous decision with imperfect information.", nashOutcome:"Platoon-neutral matchups are the NE: manager plays the matchup, hitter cannot gain additional advantage. Over-reliance on platoon advantage by either side is exploitable.", insight:"The optimal managerial strategy is not always the platoon matchup — it is the strategy the opponent cannot profitably respond to. This is why elite relievers are valuable: they collapse the opponent's mixed strategy options." }, firstPitch:{ insight:"First-pitch strike rate is the highest-leverage count variable. Pitchers who get ahead 0-1 face a dramatically improved NE set across all subsequent pitches. Getting ahead first pitch is a dominant strategy for pitchers with good command." } },
  pitchOptimization: { tunneling:"Pitch tunneling exploits the batter's perceptual limitations — pitches that share a flight path until the decision point (approx. 23 feet) and then diverge create an unsolvable mixed strategy problem for the hitter. This is the physical manifestation of a Nash-dominant pitch design." },
  marketGames: { freeAgency:{ structure:"All-pay auction: multiple teams bid on a player. Highest bidder wins player at their bid price. Losers lose nothing but gain nothing.", nashOutcome:"Teams systematically overbid for top free agents relative to WAR-based value — winner's curse effect. The expected payoff for winning is negative in high-demand auctions.", insight:"The correct free agent strategy is to identify the second tier: players valued near their true WAR where competition is lower and winner's curse is minimized. Bidding on consensus top targets is a negative-EV strategy in aggregate." }, contractNegotiation:{ structure:"Sequential bargaining game: player agent makes offer, team counter-offers, repeat until agreement or deadline.", outcome:"The party with more alternatives (BATNA) and lower deadline urgency holds more leverage. Arbitration-eligible players gain leverage from the transparent comparable system.", insight:"Teams that invest in strong BATNA positions (deep farm system, internal alternatives) systematically outperform in contract negotiations by reducing the cost of walking away." }, draftCollegeVsHS:{ structure:"Prisoner's dilemma across all 30 teams: if all teams draft college-safe picks, the expected value of each team's draft is mediocre but predictable. If one team takes HS upside swings while others draft college, that team captures asymmetric upside.", nashOutcome:"League-wide NE shifts toward college players as risk aversion increases — but individual team EV is maximized by drafting HS players when the market over-weights college safety." }, draftBonusPrisonersDilemma:{ insight:"Bonus pool allocation is a coordination game. Teams that routinely exceed slot on high-upside picks and save slot elsewhere (Astros/Cardinals model) capture EV from teams that allocate evenly. The league-wide NE would be for all teams to slot correctly — but individual deviation is profitable until slot penalties eliminate the edge." } },
  simulationInsights: { fivePlayerGame:{ rules:"Goldman (2016): Five teams each offseason try to sign one of five available free agents across three tiers. Payoffs depend on which tier player each team lands and which teams they beat out.", outcomes:"Teams that commit early to top-tier targets ('go aggressive') beat teams that wait — but if all teams go aggressive, surplus value collapses. The optimal strategy depends on reading opponent intent.", oaklandStrategy:"The A's historically exploited the NE breakdown by targeting Tier 2 players at Tier 3 prices when all competitors were bidding on Tier 1 — positive EV through strategic differentiation.", troutParadox:"Mike Trout's below-market extensions represent a deviation from player-optimal strategy — but reveal that non-monetary payoffs (location, stability, personal preference) alter the true utility function.", insight:"The offseason market is not a simultaneous auction — it is a sequential game with private information about each team's valuation and budget. Teams that signal false valuations (poker strategy) gain systematic advantages." } },
  nextMoneyball: { thesis:"Swartz (SABR 2013) argued that game theory is the next frontier of baseball analytics — the Moneyball era identified market inefficiencies in observable stats (OBP), but the next edge lies in strategic interaction: how pitchers and hitters adapt to each other in real time.", swartz2013:"Identified mixed strategy equilibria in pitch selection by count. Found systematic deviations from Nash in both pitcher and hitter behavior — exploitable edges that persist because they require behavioral change, not just information.", marketEdge:"The deepest edge in modern baseball: teams that train pitchers and hitters to play closer to mixed strategy equilibria will gain measurable performance improvements over teams relying on heuristics and scouting intuition alone.", studeman2013:"Showed that first-pitch strategy is a dominant factor in game outcomes — teams systematically underweight first-pitch strike investment in pitcher development.", prediction:"The next Moneyball will be a team that systematically uses game theory to optimize in-game decision-making: pitch sequencing, defensive shifts, lineup construction, and bullpen deployment simultaneously." },
};

export const BEHAVIORAL_BIASES = {
  confirmationBias: { definition:"The tendency to search for, interpret, and recall information in a way that confirms one's pre-existing beliefs.", scoutingApplication:"Scouts who've labeled a player as a 'bust' or 'can't miss' filter subsequent observations through that lens. Once a grade is set mentally, contradictory evidence is discounted.", analystApplication:"Analysts who build a model favoring a player will dismiss Statcast data that contradicts the model rather than updating the model.", counterMeasure:"Pre-commitment to explicit decision criteria before seeing a player. Structured adversarial review — assign one scout to argue against the consensus.", source:"Kahneman (2011) Thinking Fast and Slow; confirmed in scouting contexts by Lewis (2003) Moneyball." },
  recencyBias: { definition:"Overweighting recent events relative to base rates when making probability estimates.", scoutingApplication:"A prospect who goes 0-for-4 in the game a scout attends gets a lower hit tool grade than his season-long .310 average justifies.", draftApplication:"Teams reach for players who had strong spring performances over players with better 3-year track records but mediocre recent games.", counterMeasure:"Weight multi-year samples over in-person observation windows. Explicit regression-to-mean adjustments in projection models.", source:"Tversky & Kahneman (1974) Judgment Under Uncertainty; applied in fantasy/DFS literature extensively." },
  lossAversion: { definition:"Losses loom approximately 2x larger than equivalent gains in human psychology (Kahneman-Tversky Prospect Theory).", tradeApplication:"Teams are reluctant to trade prospects they already own even when WAR calculations clearly favor the trade — endowment effect on farm assets.", analystApplication:"GMs overvalue existing roster players relative to available alternatives — the 'sunk cost' of previous investment distorts current decision-making.", counterMeasure:"Pre-mortem analysis: assume the trade/signing failed — what would the reason be? Forces explicit acknowledgment of downside scenarios.", source:"Kahneman & Tversky (1979) Prospect Theory; Thaler (1980) Mental Accounting." },
  anchoringBias: { definition:"Over-reliance on the first piece of information encountered when making decisions.", draftApplication:"Early consensus rankings anchor team boards even when internal models produce different values. Teams rarely deviate more than 5 spots from consensus despite divergent internal grades.", tradeApplication:"First offer in a trade sets the anchor — teams that receive first offers consistently outperform teams that make first offers in outcome analysis.", counterMeasure:"Develop internal rankings completely before consuming external sources. Make first offers in negotiations when internal value is higher than expected market anchor.", source:"Tversky & Kahneman (1974); extensively documented in negotiation research." },
  elFarolEffect: { definition:"Arthur (1994): El Farol bar problem — if everyone uses the same prediction model to decide whether to attend (and avoid if expected crowded), the model destroys itself. Bounded rationality leads to heterogeneous strategies.", baseballApplication:"The market for undervalued player types (OBP in Moneyball era) corrects when all teams adopt the same inefficiency-targeting model. The edge disappears the moment it becomes consensus.", minorityGame:"The optimal fantasy/market strategy is the minority strategy: winning requires identifying what the majority is doing and doing the opposite. Being correct but consensus adds zero value.", implication:"SKIP's edge is identifying metrics and player types that the majority of the market is either ignoring or systematically mispricing — the moment a metric becomes universally adopted, its predictive alpha goes to zero.", boundedRationality:"Teams and analysts cannot process all available information optimally — they use heuristics. SKIP systematically models these heuristics to predict where market mispricing will occur." },
  fantasyPsychology: { gladwellTest:"Fantasy baseball is a test of whether you can overcome cognitive biases faster than 11 other people in your league — skill is real but manifests as bias-avoidance, not prediction accuracy.", winProbability:"Expected wins in a standard 12-team roto league: 8.33%. Consistent 60%+ win rates over 5+ seasons reflect genuine skill, not variance. But most owners mistake 2-3 year runs for skill.", correlated:"DFS optimal lineups are correlated stacks (same game, same team) because weather/pitching matchup affects all players on a team simultaneously. Uncorrelated lineups minimize variance but also minimize upside.", biasesInFantasy:{ nameism:"Drafting recognizable names over equal statistical profiles — veteran bias is measurable in ADP across all platforms.", positionScarcity:"Overvaluing positional scarcity (C, SS) relative to actual statistical contribution — catchers are consistently overdrafted relative to WAR.", streakChasing:"Buying high on streaking players at precisely the moment regression-to-mean is most likely — recency bias in its purest fantasy form.", sunkCost:"Refusing to drop players drafted in early rounds even after evidence of injury or underperformance — endowment effect on roster assets." } },
};

export const DRAFT_INTELLIGENCE = {
  structure: { rounds:20, totalPicks:'~600 (varies by comp picks)', comparison:{ NFL:'7 rounds, ~260 picks. Higher bust rate but larger per-pick dollar value. MLB has 5-7 year development window vs NFL 1-2.', NBA:'2 rounds, 60 picks. Near-zero picks beyond round 1 reach MLB. International market more important in NBA.', NHL:'7 rounds, ~217 picks. Most similar to MLB in development timeline and international alternative.' }, bonusPools:'Teams assigned bonus pool based on draft position. Exceeding pool triggers luxury tax-style penalties. Encourages slot deals and draft strategy arbitrage.', typicalPath:'HS pick: 3-5 years to MLB. College pick: 2-3 years. Elite college pitchers can debut within 1 year.', lotterySystem:'No lottery — worst records pick highest, giving tanking incentive similar to NBA but moderated by competitive balance picks.', history:'Draft established 1965. Pre-draft era: teams signed amateurs freely — wealthy franchises dominated. CBA reforms (2012, 2016, 2022) progressively limited spending to level playing field.' },
  passanPlan: { premise:'ESPN / Jeff Passan (2019): The MLB draft is structurally broken — it rewards losing, punishes development investment, and fails to create a true market for amateur talent.', howItWorks:['Eliminate draft entirely for domestic amateurs — all players become free agents at age 16-18.','Implement hard international spending pools for all amateurs (domestic + international unified market).','Revenue sharing tied to player development success metrics, not draft position.','Competitive balance preserved through luxury tax escalation, not draft order.'], legalStatus:'Viable under CBA — draft structure is collectively bargained, not statutory. Requires MLBPA and owners to agree.', tradeoff:'True free market for amateurs eliminates tanking incentive but creates financial arms race where wealthy franchises dominate amateur market.', discussed:'Discussed in 2022 CBA negotiations — not adopted. International pool reforms partially address the issue.' },
  draftEfficiency: { definition:'Nandakumar & Wharton (2017): A "perfect draft" is one where each pick selected was the best available player at that position in the draft class, in hindsight.', methodology:'Compare actual selections against player career value (WAR or points equivalent). Calculate % of picks that were the best available at each slot.', efficiencyMetric:'Draft Efficiency % = (Picks that were best available) / (Total picks). League average is ~18-22% — most teams do dramatically worse than chance would suggest.', mlbApplication:'Teams with strong scouting infrastructure (Cardinals, Dodgers, Rays) consistently show higher draft efficiency over 10-year windows. Analytics integration correlates with improved efficiency.', keyInsight:'Draft efficiency improves most dramatically in rounds 3-10 — round 1 is adequately scouted by all teams. The edge is in identifying late-round value where information asymmetry is highest.', nhFinding:'NHL study found franchises in the bottom quartile of draft efficiency consistently missed playoffs regardless of other roster construction decisions — draft is a long-term talent lever, not a short-term fix.' },
  scoutingFramework: { oldSchool:{ philosophy:'Project current tools to peak — raw athleticism, physicality, and measurable tools (velocity, exit velocity) are primary. Character and makeup are heavy qualitative filters.', tools:['Hit tool (contact ability)','Power (raw and game)','Run (speed)','Arm (strength and accuracy)','Field (glove and range)'] }, moneyballModel:{ philosophy:'College players over HS — lower variance, shorter development timeline, better statistical track record to evaluate. OBP and plate discipline over traditional tools.', limitations:'Ignores ceiling — college safe picks cluster in the middle of career WAR distributions. High-ceiling HS picks dominate the top of all-time WAR lists.' }, modernModel:{ approach:'Hybrid: Statcast measurables (bat speed, arm strength via Trackman, spin rate) + traditional scouting + college statistical quality adjustment. Aims to identify ceiling while reducing bust rate.', riskDimension:'College vs HS is now a risk-adjusted return question, not a binary preference. Teams model expected WAR distribution, not just expected WAR.' } },
  strategies: { bestPlayerAvailable:'Draft the highest-graded player regardless of position need. Maximizes expected draft class WAR. Optimal in most models.', positionOfNeed:'Draft for organizational roster gaps. Sub-optimal in WAR terms but can accelerate MLB-ready timelines for contending teams.', signabilityAdjusted:'Shade grades downward for players with high slot demands or college commitment leverage. Maximizes expected player signed per pool dollar.', internationalArbitrage:'Spend less on domestic draft (take signable players at slots), redirect savings toward IFA market where dollar-per-WAR is historically higher.', pitchingHeavy:'Load on arms early — pitching development is the primary organizational lever. Pitching scarcity at MLB level means pitcher WAR commands premium.' },
  bargainingFindings: { finding1:'Teams systematically underpay picks 1-10 relative to their true value — slot system compresses compensation for elite talent.', finding2:'HS players 3-5% more likely to reach MLB when drafted by teams with strong pitching development infrastructure — organization matters for development outcome.', finding3:'College players drafted in rounds 2-5 show highest dollar-per-WAR efficiency — late-round college value is the most persistent market inefficiency in the draft.', implication:'The optimal draft strategy combines: (1) best player available in round 1, (2) over-slot HS upside in rounds 2-3 with saved pool dollars, (3) college safe picks in rounds 4-10 for organizational depth.' },
};

export const PROJECTION_SYSTEMS = {
  methodology:"All major projection systems use regression-to-mean of past performance weighted by recency, adjusted for age curves, park factors, and playing time estimates. They predict mean outcomes — not distributions of outcomes.",
  systems:[
    { name:'Steamer',   creator:'Siers & Kenelly',  notes:'Primarily regression-based. Weights last 3 years. Best performer in historical accuracy studies.' },
    { name:'ZiPS',      creator:'Dan Szymborski',   notes:'ZiPS projects career arcs, not just one-year outcomes. Uses similarity scores and historical aging curves.' },
    { name:'PECOTA',    creator:'BP / Nate Silver',  notes:'Introduced percentile distributions — projects 10th/50th/90th percentile outcomes, not just means. Enables risk-adjusted decision making.' },
    { name:'ATC',       creator:'Composite',        notes:'Average of major systems. Reduces variance by ensemble method. Best single-year mean predictor in most studies.' },
    { name:'THE BAT',   creator:'Derek Carty',      notes:'Daily fantasy optimized. Weights recent performance more heavily — better for short-term decisions, worse for full season.' },
    { name:'Fangraphs', creator:'FanGraphs Staff',   notes:'Steamer + ZiPS ensemble with FG park factors. Used as default projection in FG player pages.' },
    { name:'SKIP TPVI', creator:'SKIP Engine',       notes:'Rule-based in-season only. Not a preseason projection system — evaluates current production quality against historical benchmarks in real time.' },
  ],
  auctionFramework:{ pricePoints:'In standard $260 auction leagues, each win above replacement above the baseline produces approximately $10 in value. Replacement-level players are worth $1 (minimum bid).', profitMetric:'Profit = Projected $ value - Draft $ cost. Positive profit players create competitive advantage; negative profit players destroy it.', indifference:'At the margin, a player priced at exactly their projected value is an indifference point — taking them does not help or hurt relative to alternatives.', categoriesVsPoints:'Roto categories distort player valuation vs points leagues. Stolen bases have near-zero value in points formats but 15-20% of positional value in standard roto — creates completely different optimal draft strategies.' },
  gameTheoryAngle:"Projection systems are public information — in efficient markets (large expert leagues, DFS), alpha from superior projections is near zero. The real edge is identifying systematic biases in how the market translates projections into prices: which player types are consistently over/under-priced relative to their true projection.",
  skipApplication:"SKIP's TPVI and CAS metrics are real-time production quality scores, not projection systems. They answer 'how good is this player performing now?' — projection systems answer 'what will this player do over a full season?' Both are necessary for complete player evaluation.",
};

/* ── eFV methodology copy — rendered on Knowledge → Future Value ────────
   The actual grade computation lives in src/engine/skip.js (computeFV,
   projectedWAR, fvRiskBand, fvETA); this is just the plain-English writeup
   of that same math, kept as data so the copy can be edited without
   touching the engine, matching the pattern every other Knowledge tab
   already uses (DRAFT_INTELLIGENCE, PROJECTION_SYSTEMS, etc). */
export const FV_METHODOLOGY = {
  whatItIs:"SKIP's Future Value grade (eFV) projects a prospect's realistic career outcome on the traditional 20-80 scouting scale — but unlike a scout's shorthand, eFV isn't rounded to the nearest 5. Two prospects a few ranks apart get two different numbers instead of the same tied grade.",
  inputs:[
    { label:'Board Position', weight:'Primary',   desc:"A prospect's rank in SKIP's combined Top-100 (batters and pitchers share one list). Maps onto a smooth curve — roughly 70 at #1 down to the low 40s at #100 — matching the shape of published industry Top-100 lists rather than a flat distribution." },
    { label:'Level-Relative Performance', weight:'Secondary', desc:"How far a prospect's current OPS (hitters) or ERA / K-rate (pitchers) sits from the median of SKIP's tracked pool at a comparable stage. Deliberately small — a week of stats can't override the underlying rank — but large enough that a real breakout or slump moves the number." },
    { label:'Age-for-Level', weight:'Tertiary', desc:'A player performing young for their level gets a small bump — more runway before a theoretical peak. Old-for-level gets a small discount — less projection remaining.' },
  ],
  outputRange:'35–70 · whole numbers only',
  whyContinuous:"A bucketed grade (45, 50, 55…) works fine for one scout describing one player out loud. It falls apart once you're differentiating 100 of them — dozens end up tied with no way to rank within the tie. Keeping the output continuous doesn't pretend scouting is more precise than it is; the underlying inputs (rank, stat line, age) are exact, so there's no reason to round the output.",
  warAnchors:[[35,0.3],[40,1.0],[45,2.5],[50,4.5],[55,7.0],[60,10.0],[65,12.5],[70,15.0]],
  riskBands:[
    { band:'Low',    color:'teal',  desc:'Advanced level (AAA / MLB-adjacent), age at or above the typical benchmark for that level. Track record is established; variance is mostly in ceiling, not floor.' },
    { band:'Medium', color:'amber', desc:'Mid-level (A+ through AA), age roughly in line with level expectations. Standard developmental variance.' },
    { band:'High',   color:'rust',  desc:'Lower-level (Rookie / A ball) and/or meaningfully young for level. Long developmental runway still ahead — highest bust rate, but also the widest range of outcomes.' },
  ],
  movers:"eFV recomputes automatically every time live MLB stats refresh — it isn't a number someone re-types by hand. The eFV Movers panel on the Prospects tab diffs that live grade against a fixed preseason snapshot, so every mover shown there is driven by real, in-season performance drift.",
  outcomeGrounding:"SKIP validates the eFV curve the same way the Draft Big Board validates its pre-draft ranking against actual results: once a prospect graduates to the majors, their eFV at graduation and their realized production become a permanent pair in the record, not a grade that quietly disappears. A model whose top grades don't outproduce its lower ones over time is a model that needs recalibrating.",
};

export const PLAYER_GRADE_RUBRIC = {
  A:{ label:'Franchise / Elite', A1_pitcher:'Top-5 SP: ERA sub-3.00, 200+ K, WHIP under 1.10, FIP-ERA negative. Ace / Cy Young contender.', A2_pitcher:'Top-15 SP or elite RP closer: ERA 3.00-3.50, 180+ K, elite command. All-Star caliber.', A1_hitter:'MVP-caliber: OPS 1.000+, 40+ HR or .330+ AVG, top-5 WAR. Generational talent.', A2_hitter:'All-Star: OPS .950+, 30+ HR, consistent 5+ WAR. Clear organizational cornerstone.' },
  B:{ label:'Above-Average / Starting Caliber', B1_pitcher:'Solid #2/#3 SP: ERA 3.50-4.00, 160+ K, WHIP 1.10-1.25. Above-average innings eater.', B2_pitcher:'League-average SP or quality setup RP: ERA 4.00-4.50, 140+ K. Back-end rotation / high-leverage relief.', B1_hitter:'Above-average regular: OPS .850-.950, 20-30 HR, 3-5 WAR. Clear MLB starter at a premium position.', B2_hitter:'Solid regular: OPS .780-.850, 15-20 HR, 2-3 WAR. Everyday player at non-premium position.' },
  C:{ label:'Fringe / Depth', C1_pitcher:'Back-end SP or middle relief: ERA 4.50-5.00, 100-140 K. Depth starter or situational RP.', C2_pitcher:'Roster filler: ERA 5.00+, limited K, significant command issues. Minor league depth or AAAA arm.', C1_hitter:'Platoon / bench player: OPS .720-.780, 10-15 HR, 1-2 WAR. Useful bench bat or part-time starter.', C2_hitter:'Replacement level: OPS .650-.720, 5-10 HR, below 1 WAR. Organizational depth only.' },
  D:{ label:'Organizational / Developmental', description:'Players who provide depth, development value, or defensive utility without significant offensive/pitching production.', pitcher_requirements:'Below replacement ERA (5.00+), minimal K rate, poor command. Value is developmental ceiling only or organizational depth.', hitter_requirements:'OPS below .650, limited power or on-base, negative or zero WAR. Defensive utility only at premium positions (C, SS, CF) can extend value.', catcher_requirements:'Catchers grade one tier higher than equivalent offensive profile due to positional scarcity and defensive value — a D-grade bat at C can be C1-grade overall with elite framing.', character:'Professional makeup, coachability, and work ethic are required minimums at all grades — character failure can downgrade any tier to non-roster.' },
  skipMapping:{ A1:{ skip:'PRIORITY ACQ', tpviRange:[88,99], color:'#2A7B6B', description:'Franchise-altering talent. Acquire at near any cost.' }, A2:{ skip:'STRONG BUY', tpviRange:[78,87], color:'#2A7B6B', description:'All-Star caliber. Strong acquisition target.' }, B1:{ skip:'MONITOR', tpviRange:[65,77], color:'#C17D2C', description:'Above-average. Acquire at right price.' }, B2:{ skip:'HOLD', tpviRange:[52,64], color:'#C17D2C', description:'Solid regular. Hold; buy only if cheap.' }, C1:{ skip:'HOLD', tpviRange:[38,51], color:'#4A5E7A', description:'Depth piece. Do not overpay.' }, C2:{ skip:'AVOID', tpviRange:[25,37], color:'#B54A2A', description:'Replacement level. Avoid in competitive markets.' }, D:{ skip:'AVOID', tpviRange:[0,24], color:'#B54A2A', description:'Organizational depth only. No acquisition value.' } },
};

export const FOLLOW_LIST = [
  { name:'Kiley McDaniel', handle:'kileymcd', category:'Media & Scouting', bio:'ESPN Baseball Insider. Former FanGraphs & four MLB teams.' },
  { name:'Joe Doyle', handle:'JoeDoyleMLB', category:'Media & Scouting', bio:'Founder/Host, Over-Slot. Former MLB consulting scout.' },
  { name:'JJ Cooper', handle:'jjcoop36', category:'Media & Scouting', bio:'Editor-In-Chief, Baseball America.' },
  { name:'Baseball America', handle:'BaseballAmerica', category:'Media & Scouting', bio:'Coverage and authority on all levels of baseball for 40+ years.' },
  { name:'MLB Pipeline', handle:'MLBPipeline', category:'Media & Scouting', bio:"MLB's official home of Minor League and Draft prospect rankings." },
  { name:'Bobby Baseball', handle:'Robert_Stangler', category:'Media & Scouting', bio:'Creator of the Stitches Podcast. Prospect insider for MLB, NPB, KBO.' },
  { name:'Dan Szymborski', handle:'DSzymborski', category:'Media & Scouting', bio:'Senior Writer, FanGraphs. ESPN contributor. Creator of ZiPS.' },
  { name:'Sarah Langs', handle:'SlangsOnSports', category:'Media & Scouting', bio:'MLB.com. Previously ESPN, CSN Chicago, SNY, Mets Blog.' },
  { name:'Evan Petzold', handle:'EvanPetzold', category:'Media & Scouting', bio:'Detroit Tigers coverage — recaps, news, roster updates, analysis.' },
  { name:'Down on the Farm', handle:'downonthefarm12', category:'Media & Scouting', bio:'Newsletter covering MiLB analysis, news, prospects, player development.' },
  { name:'Running From The OPS', handle:'OPS_BASEBALL', category:'Media & Scouting', bio:"Independent Rays and org MiLB coverage. Former Rays Baseball." },
  { name:'Yakyu Cosmopolitan', handle:'yakyucosmo', category:'Media & Scouting', bio:'Covering Japanese baseball in English.' },

  { name:'Tangotiger', handle:'tangotiger', category:'Analytics & R&D', bio:"MLB Sr. Data Architect. Author, The Book." },
  { name:'Cameron Grove', handle:'Pitching_Bot', category:'Analytics & R&D', bio:'Cleveland Guardians R&D. Former astrophysicist, based in London.' },
  { name:'Ben Resnic', handle:'BenResnic', category:'Analytics & R&D', bio:'R&D, Atlanta Braves. Syracuse alum.' },
  { name:'Camden Kay', handle:'ck_camden', category:'Analytics & R&D', bio:'Texas Rangers R&D. Co-author of mlbplotR, baseballr contributor.' },
  { name:'Roderick Dabovich', handle:'rjdabo25', category:'Analytics & R&D', bio:'San Francisco Giants. Push performance / DB9.' },
  { name:'Emilio Martinez', handle:'E_Mart97', category:'Analytics & R&D', bio:'Coordinator of Performance Science, Colorado Rockies.' },
  { name:'SIS Baseball', handle:'sis_baseball', category:'Analytics & R&D', bio:'Analytics for MLB teams and media. Defensive Runs Saved, Fielding Bible.' },
  { name:'BaseballCloud', handle:'BaseballCloudUS', category:'Analytics & R&D', bio:'Player-tracking data platform, part of the Win Reality product suite.' },
  { name:'Algorithmic Athlete', handle:'AlgoAthlete', category:'Analytics & R&D', bio:'Creating data visualizations to understand sports.' },
  { name:'Past The Eye Test', handle:'PastTheEyeTest', category:'Analytics & R&D', bio:'Data visualization and analysis for baseball.' },
  { name:'Codify', handle:'CodifyMLB', category:'Analytics & R&D', bio:'Heat maps for game planning and pitch design, trusted by 300+ MLB pitchers.' },
  { name:'Ross Jensen', handle:'rossjensen', category:'Analytics & R&D', bio:'CEO, StatLine Scout & Prospects Live.' },
  { name:'Nostra Thomas', handle:'TomTrudeau', category:'Analytics & R&D', bio:'Projections. Co-owner, StatLine Scout. Former MLB & MiLB.' },
  { name:'Thomas Nestico', handle:'TJStats', category:'Analytics & R&D', bio:'Independent baseball analytics.' },
  { name:'Mays Copeland', handle:'MaysCopeland', category:'Analytics & R&D', bio:'Builds fantasy tools — DraftKick.com and TheMVP.app.' },

  { name:'Jack Lambert', handle:'jacklambert_', category:'Player Development', bio:'Director of Baseball Operations, Driveline Baseball.' },
  { name:'Travis Buck', handle:'TBuckUO', category:'Player Development', bio:'Director of Operations, Oregon Baseball.' },
  { name:'Ryan Lovato', handle:'Rylo252', category:'Player Development', bio:'Assistant Coach, Grand Canyon Baseball.' },
  { name:'Joey Cunha', handle:'joeycunha', category:'Player Development', bio:'Founder, The Farm System. Sports science for MLB orgs.' },
  { name:'Mariners Player Development', handle:'MsPlayerDev', category:'Player Development', bio:'Official Player Development account of the Seattle Mariners.' },

  { name:"MLB's Arizona Fall League", handle:'MLBazFallLeague', category:'Team & League Orgs', bio:"Official account of MLB's Arizona Fall League." },
  { name:'SABR', handle:'sabr', category:'Team & League Orgs', bio:'The Society for American Baseball Research.' },

  { name:'Corbin Carroll', handle:'corbin_carroll', category:'Players', bio:'Arizona Diamondbacks.' },
  { name:'Termarr Johnson', handle:'JohnsonTermarr', category:'Players', bio:'Professional player, Pittsburgh Pirates organization.' },

  { name:'John Creel', handle:'JohnCreel', category:'Front Office & Agents', bio:'MLB Player Agent, Simon Sports. Formerly Mariners.' },
  { name:'Ned Colletti', handle:'realnedcolletti', category:'Front Office & Agents', bio:'40-year MLB executive. Former Dodgers GM. Author, The Big Chair.' },

  { name:'House of Sparky', handle:'HouseofSparky', category:'Independent Voices', bio:'ASU Sun Devils sports news and analysis.' },
  { name:'Would it dong?', handle:'would_it_dong', category:'Independent Voices', bio:'How many parks would that hit have gone out in?' },
  { name:'Zak Ibrahim', handle:'ZakIbrahimOnAir', category:'Independent Voices', bio:'Sports Director at Meridian Media.' },
  { name:'Ian Cohen', handle:'iancohen04', category:'Independent Voices', bio:'Baseball commentary.' },
];

export const FOLLOW_LIST_CATEGORIES = [
  'Media & Scouting', 'Analytics & R&D', 'Player Development',
  'Team & League Orgs', 'Players', 'Front Office & Agents', 'Independent Voices',
];
